const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index-v2.html'), 'utf8');
const ux = fs.readFileSync(path.join(root, 'ux-v2.js'), 'utf8');
const map = fs.readFileSync(path.join(root, 'global-asset-map.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'global-asset-map.css'), 'utf8');

assert.match(html, /data-v2-mode="map"[^>]*>자산지도</);
assert.match(html, /global-asset-map\.css/);
assert.match(html, /global-asset-map\.js\?v=global_asset_map_20260910b/);
assert.match(html, /ux-v2\.js\?v=global_asset_map_20260910b/);
assert.ok(html.indexOf('js/global-asset-map-core.js') < html.indexOf('global-asset-map.js'));
assert.ok(html.indexOf('global-asset-map.js') < html.indexOf('ux-v2.js'));
assert.match(ux, /global-asset-map-mode/);
assert.match(ux, /GlobalAssetMap\.activate/);
assert.match(ux, /GlobalAssetMap\.deactivate/);
assert.match(ux, /'portfolio', 'map', 'capital', 'search'/);
assert.match(ux, /mode !== 'search'.*delete\('query'\)/);
assert.match(map, /사각 도트 세계지도/);
assert.match(map, /__ra_asset_map_snapshot/);
assert.match(map, /maplibre-gl@5\.7\.1/);
assert.match(map, /sha384-[A-Za-z0-9+/=]+/);
assert.match(map, /tile\.openstreetmap\.org/);
assert.doesNotMatch(map, /basemaps\.cartocdn\.com/);
assert.doesNotMatch(map, /API KEY REQUIRED/);
assert.match(map, /pixelLandHtml/);
assert.doesNotMatch(map, /continentPaths/);
assert.match(map, /world-cluster[^\n]+<circle/);
assert.match(map, /fallback-dot[^\n]+<circle/);
assert.doesNotMatch(map, /fallback-dot[^\n]+<rect/);
assert.match(map, /zoomend/);
assert.match(map, /change:resolution/);
assert.match(map, /shouldReturnToWorld/);
assert.match(map, /AbortController/);
assert.match(map, /generation !== state\.generation/);
assert.match(map, /loadStatus:\s*'idle'/);
assert.match(map, /state\.loadStatus === 'loading'/);
assert.match(map, /function restore\(\)/);
assert.doesNotMatch(map, /restore:\s*render/, 'restore must not render an uninitialized empty dataset');
assert.doesNotMatch(map, /_state:\s*state/, 'protected rows must not be exposed as a production debug API');
assert.match(css, /@media \(max-width: 760px\)/);
assert.match(css, /min-height: 48px/);
assert.match(css, /\.world-grid rect/);
assert.match(css, /\.world-cluster circle/);
assert.match(css, /\.fallback-dot circle/);
assert.match(css, /\.global-map-marker[^}]+border-radius:\s*50%/);
assert.match(css, /\.global-map-canvas > \.global-maplibre[^}]+position:\s*absolute !important[^}]+height:\s*100%/);
assert.match(css, /background: #131715/);
assert.match(css, /prefers-reduced-motion:[^}]+\)[\s\S]*?animation:\s*none/);

console.log('global-asset-map integration tests passed');
