-- Commercial Real Estate Intelligence V2 seed
PRAGMA foreign_keys = ON;
BEGIN IMMEDIATE;

INSERT INTO units(unit_code, dimension_code, name_ko, symbol, si_multiplier) VALUES
 ('KRW','CURRENCY','원','원',1),
 ('KRW_100M','CURRENCY','억원','억원',100000000),
 ('M2','AREA','제곱미터','㎡',1),
 ('PYEONG','AREA','평','평',3.305785),
 ('PERCENT','RATIO','퍼센트','%',0.01),
 ('BPS','RATIO','베이시스포인트','bp',0.0001),
 ('COUNT','COUNT','건·개','건',1),
 ('ROOM','COUNT','객실','실',1),
 ('MW','POWER','메가와트','MW',1000000),
 ('DAY','DURATION','일','일',86400),
 ('MONTH','DURATION','개월','개월',NULL),
 ('INDEX','INDEX','지수','',NULL),
 ('KRW_PER_M2','UNIT_PRICE','원/㎡','원/㎡',NULL),
 ('KRW_PER_PYEONG','UNIT_PRICE','원/평','원/평',NULL);

INSERT INTO asset_classes(asset_class_id, code, name_ko, parent_id, sort_order) VALUES
 ('ac_commercial','COMMERCIAL_REAL_ESTATE','상업용 부동산',NULL,0),
 ('ac_office','OFFICE','오피스','ac_commercial',10),
 ('ac_hotel','HOTEL','호텔·리조트','ac_commercial',20),
 ('ac_dc','DATA_CENTER','데이터센터','ac_commercial',30),
 ('ac_logistics','LOGISTICS','물류센터','ac_commercial',40),
 ('ac_living','LIVING','리빙','ac_commercial',50),
 ('ac_multifamily','MULTIFAMILY','임대주택·멀티패밀리','ac_living',51),
 ('ac_coliving','COLIVING','코리빙','ac_living',52),
 ('ac_student','STUDENT_HOUSING','학생주거','ac_living',53),
 ('ac_senior','SENIOR_LIVING','시니어리빙','ac_living',54),
 ('ac_retail','RETAIL','리테일','ac_commercial',60),
 ('ac_healthcare','HEALTHCARE','헬스케어','ac_commercial',70),
 ('ac_kic','KNOWLEDGE_INDUSTRY_CENTER','지식산업센터','ac_commercial',80),
 ('ac_mixed','MIXED_USE','복합개발','ac_commercial',90),
 ('ac_leisure','LEISURE','레저·골프','ac_commercial',100),
 ('ac_land','DEVELOPMENT_LAND','상업용 개발부지','ac_commercial',110),
 ('ac_other','OTHER_ALTERNATIVE','기타 대체자산','ac_commercial',999);

-- --------------------------------------------------------------------------
-- V2.2 extensible measurement taxonomy
-- --------------------------------------------------------------------------
INSERT INTO measurement_definitions(
 measurement_definition_id,code,name_ko,parent_definition_id,dimension_code,
 measurement_family,canonical_unit_code,aggregation_behavior,sector_scope,
 definition_text,is_abstract
) VALUES
 ('md_area','AREA','면적',NULL,'AREA','AREA','M2','NON_ADDITIVE','CROSS_SECTOR','면적 측정의 최상위 추상 개념',1),
 ('md_land_family','LAND_SITE_AREA','토지·부지 면적','md_area','AREA','LAND_SITE','M2','NON_ADDITIVE','CROSS_SECTOR','토지·필지·대지·사업부지의 면적 계열',1),
 ('md_reg_family','REGULATORY_BUILDING_AREA','건축·법정 면적','md_area','AREA','REGULATORY_BUILDING','M2','NON_ADDITIVE','CROSS_SECTOR','인허가·건축물대장·설계 기준 건축 면적 계열',1),
 ('md_floor_family','FLOOR_SPACE_AREA','층·공간 면적','md_area','AREA','FLOOR_SPACE','M2','NON_ADDITIVE','CROSS_SECTOR','동·층·구역 단위 공간 면적 계열',1),
 ('md_lease_family','LEASING_OCCUPANCY_AREA','임대·점유 면적','md_area','AREA','LEASING_OCCUPANCY','M2','NON_ADDITIVE','CROSS_SECTOR','임대가능·임차·공실·전용·공용 면적 계열',1),
 ('md_supply_family','DEVELOPMENT_SUPPLY_AREA','개발·공급 면적','md_area','AREA','DEVELOPMENT_SUPPLY','M2','NON_ADDITIVE','CROSS_SECTOR','공급·분양·계약 기준 면적 계열',1),
 ('md_logi_family','LOGISTICS_FUNCTIONAL_AREA','물류 기능 면적','md_area','AREA','LOGISTICS','M2','NON_ADDITIVE','SECTOR_SPECIFIC','보관·적재·하역·도크·램프 등 물류 기능 공간',1),
 ('md_dc_family','DATA_CENTER_FUNCTIONAL_AREA','데이터센터 기능 면적','md_area','AREA','DATA_CENTER','M2','NON_ADDITIVE','SECTOR_SPECIFIC','화이트스페이스·데이터홀·전기·기계·지원 공간',1),
 ('md_retail_family','RETAIL_FUNCTIONAL_AREA','리테일 기능 면적','md_area','AREA','RETAIL','M2','NON_ADDITIVE','SECTOR_SPECIFIC','영업·매장·후방·F&B 공간',1),
 ('md_hosp_family','HOSPITALITY_LIVING_AREA','호텔·리빙 기능 면적','md_area','AREA','HOSPITALITY_LIVING','M2','NON_ADDITIVE','SECTOR_SPECIFIC','객실·세대·어메니티·공용·후방 공간',1),

 ('md_unclassified_area','UNCLASSIFIED_AREA','미분류 면적','md_area','AREA','AREA','M2','NON_ADDITIVE','CROSS_SECTOR','원문에서 면적임은 확인됐지만 의미 유형이 미확정인 값',0),
 ('md_land_area','LAND_AREA','토지면적','md_land_family','AREA','LAND_SITE','M2','ADDITIVE','CROSS_SECTOR','토지 자체의 면적',0),
 ('md_parcel_area','PARCEL_AREA','필지면적','md_land_family','AREA','LAND_SITE','M2','ADDITIVE','CROSS_SECTOR','지적상 개별 필지의 면적',0),
 ('md_site_area','SITE_AREA','대지면적','md_land_family','AREA','LAND_SITE','M2','ADDITIVE','CROSS_SECTOR','건축 대상 대지의 면적',0),
 ('md_project_site_area','PROJECT_SITE_AREA','사업부지면적','md_land_family','AREA','LAND_SITE','M2','ADDITIVE','CROSS_SECTOR','개발사업 전체 사업부지의 면적',0),
 ('md_developable_area','DEVELOPABLE_SITE_AREA','개발가능면적','md_land_family','AREA','LAND_SITE','M2','SEMI_ADDITIVE','CROSS_SECTOR','규제·물리조건을 반영한 개발 가능 부지 면적',0),
 ('md_landscape_area','LANDSCAPE_AREA','조경면적','md_land_family','AREA','LAND_SITE','M2','ADDITIVE','CROSS_SECTOR','조경으로 계획·조성된 면적',0),
 ('md_road_donation_area','ROAD_DONATION_AREA','도로·기부채납면적','md_land_family','AREA','LAND_SITE','M2','ADDITIVE','CROSS_SECTOR','도로 또는 기부채납 대상 면적',0),

 ('md_footprint_area','BUILDING_FOOTPRINT_AREA','건축면적','md_reg_family','AREA','REGULATORY_BUILDING','M2','ADDITIVE','CROSS_SECTOR','건축법상 수평투영 건축면적',0),
 ('md_gfa','GROSS_FLOOR_AREA','연면적','md_reg_family','AREA','REGULATORY_BUILDING','M2','ADDITIVE','CROSS_SECTOR','건축물 각 층 바닥면적의 합계',0),
 ('md_gfa_above','ABOVE_GROUND_GFA','지상 연면적','md_gfa','AREA','REGULATORY_BUILDING','M2','ADDITIVE','CROSS_SECTOR','지상층 바닥면적 합계',0),
 ('md_gfa_below','BELOW_GROUND_GFA','지하 연면적','md_gfa','AREA','REGULATORY_BUILDING','M2','ADDITIVE','CROSS_SECTOR','지하층 바닥면적 합계',0),
 ('md_far_gfa','FAR_CALCULATION_AREA','용적률 산정 연면적','md_reg_family','AREA','REGULATORY_BUILDING','M2','ADDITIVE','CROSS_SECTOR','용적률 계산에 포함되는 연면적',0),
 ('md_bcr_area','BUILDING_COVERAGE_CALCULATION_AREA','건폐율 산정면적','md_reg_family','AREA','REGULATORY_BUILDING','M2','ADDITIVE','CROSS_SECTOR','건폐율 계산에 사용되는 건축면적',0),

 ('md_floor_area','FLOOR_AREA','층별면적','md_floor_family','AREA','FLOOR_SPACE','M2','ADDITIVE','CROSS_SECTOR','특정 층 또는 층 범위의 면적',0),
 ('md_floor_plate','FLOOR_PLATE_AREA','바닥판면적','md_floor_family','AREA','FLOOR_SPACE','M2','ADDITIVE','CROSS_SECTOR','특정 층 바닥판 전체 면적',0),
 ('md_typical_floor','TYPICAL_FLOOR_AREA','기준층면적','md_floor_family','AREA','FLOOR_SPACE','M2','NON_ADDITIVE','CROSS_SECTOR','대표적인 기준층의 면적이며 층수만큼 자동 합산하지 않음',0),
 ('md_usable_area','USABLE_AREA','사용가능면적','md_floor_family','AREA','FLOOR_SPACE','M2','SEMI_ADDITIVE','CROSS_SECTOR','실제 사용 가능한 면적',0),
 ('md_exclusive_area','EXCLUSIVE_AREA','전용면적','md_floor_family','AREA','FLOOR_SPACE','M2','SEMI_ADDITIVE','CROSS_SECTOR','특정 사용자에게 전용되는 면적',0),
 ('md_common_area','COMMON_AREA','공용면적','md_floor_family','AREA','FLOOR_SPACE','M2','SEMI_ADDITIVE','CROSS_SECTOR','복수 사용자가 공동 사용하는 면적',0),
 ('md_service_area','SERVICE_AREA','서비스면적','md_floor_family','AREA','FLOOR_SPACE','M2','SEMI_ADDITIVE','CROSS_SECTOR','설비·운영 지원을 위한 서비스 공간 면적',0),
 ('md_core_area','BUILDING_CORE_AREA','코어면적','md_floor_family','AREA','FLOOR_SPACE','M2','ADDITIVE','CROSS_SECTOR','엘리베이터·계단·샤프트 등 건물 코어 면적',0),

 ('md_gla','GROSS_LEASABLE_AREA','총임대가능면적','md_lease_family','AREA','LEASING_OCCUPANCY','M2','SEMI_ADDITIVE','CROSS_SECTOR','임대 가능한 전체 면적',0),
 ('md_nla','NET_LEASABLE_AREA','순임대가능면적','md_lease_family','AREA','LEASING_OCCUPANCY','M2','SEMI_ADDITIVE','CROSS_SECTOR','공용·비임대 공간을 제외한 순임대가능면적',0),
 ('md_rentable_area','RENTABLE_AREA','임대면적','md_lease_family','AREA','LEASING_OCCUPANCY','M2','SEMI_ADDITIVE','CROSS_SECTOR','임대 산정 기준이 되는 면적',0),
 ('md_leased_area','LEASED_AREA','임차·계약면적','md_lease_family','AREA','LEASING_OCCUPANCY','M2','SEMI_ADDITIVE','CROSS_SECTOR','특정 시점에 임대차 계약된 면적',0),
 ('md_vacant_area','VACANT_AREA','공실면적','md_lease_family','AREA','LEASING_OCCUPANCY','M2','SNAPSHOT','CROSS_SECTOR','특정 시점에 임대되지 않은 면적',0),

 ('md_supply_area','SUPPLY_AREA','공급면적','md_supply_family','AREA','DEVELOPMENT_SUPPLY','M2','SEMI_ADDITIVE','CROSS_SECTOR','공급 공고 또는 사업계획상 공급면적',0),
 ('md_saleable_area','SALEABLE_AREA','분양면적','md_supply_family','AREA','DEVELOPMENT_SUPPLY','M2','SEMI_ADDITIVE','CROSS_SECTOR','분양 대상으로 산정된 면적',0),
 ('md_contract_area','CONTRACT_AREA','계약면적','md_supply_family','AREA','DEVELOPMENT_SUPPLY','M2','SEMI_ADDITIVE','CROSS_SECTOR','계약서상 전용·공용 등을 포함한 계약면적',0),

 ('md_warehouse_area','WAREHOUSE_AREA','창고면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','물류센터 내 창고 기능 공간 면적',0),
 ('md_storage_area','STORAGE_AREA','보관면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','물품 보관에 사용되는 공간 면적',0),
 ('md_effective_storage','EFFECTIVE_STORAGE_AREA','유효 적재면적','md_logi_family','AREA','LOGISTICS','M2','SEMI_ADDITIVE','SECTOR_SPECIFIC','통로·설비 등을 제외하고 실제 적재 가능한 면적',0),
 ('md_ambient_storage','AMBIENT_STORAGE_AREA','상온 보관면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','상온 조건 보관 공간 면적',0),
 ('md_cold_storage','COLD_STORAGE_AREA','저온 보관면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','냉장·저온 조건 보관 공간 면적',0),
 ('md_frozen_storage','FROZEN_STORAGE_AREA','냉동 보관면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','냉동 조건 보관 공간 면적',0),
 ('md_loading_area','LOADING_UNLOADING_AREA','하역면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','상하차·하역 작업 공간 면적',0),
 ('md_dock_area','DOCK_AREA','도크면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','차량 접안 도크 공간 면적',0),
 ('md_ramp_area','RAMP_AREA','램프면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','차량 이동용 램프 공간 면적',0),
 ('md_logi_office','LOGISTICS_OFFICE_AREA','물류 사무공간면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','물류시설 내부 사무공간 면적',0),
 ('md_logi_amenity','LOGISTICS_AMENITY_AREA','물류 편의공간면적','md_logi_family','AREA','LOGISTICS','M2','ADDITIVE','SECTOR_SPECIFIC','휴게·편의·복지 공간 면적',0),

 ('md_white_space','WHITE_SPACE_AREA','화이트스페이스 면적','md_dc_family','AREA','DATA_CENTER','M2','SEMI_ADDITIVE','SECTOR_SPECIFIC','IT 장비 배치를 위한 데이터센터 화이트스페이스 면적',0),
 ('md_data_hall','DATA_HALL_AREA','데이터홀 면적','md_dc_family','AREA','DATA_CENTER','M2','ADDITIVE','SECTOR_SPECIFIC','서버 랙이 배치되는 데이터홀의 면적',0),
 ('md_server_room','SERVER_ROOM_AREA','서버실 면적','md_dc_family','AREA','DATA_CENTER','M2','ADDITIVE','SECTOR_SPECIFIC','서버실로 구획된 공간 면적',0),
 ('md_mmr_area','MEET_ME_ROOM_AREA','MMR 면적','md_dc_family','AREA','DATA_CENTER','M2','ADDITIVE','SECTOR_SPECIFIC','통신사업자 상호접속을 위한 Meet-Me Room 면적',0),
 ('md_network_room','NETWORK_ROOM_AREA','통신·네트워크실 면적','md_dc_family','AREA','DATA_CENTER','M2','ADDITIVE','SECTOR_SPECIFIC','통신·네트워크 장비실 면적',0),
 ('md_electrical_room','ELECTRICAL_ROOM_AREA','전기실 면적','md_dc_family','AREA','DATA_CENTER','M2','ADDITIVE','SECTOR_SPECIFIC','수변전·배전 등 전기설비 공간 면적',0),
 ('md_mechanical_room','MECHANICAL_ROOM_AREA','기계실 면적','md_dc_family','AREA','DATA_CENTER','M2','ADDITIVE','SECTOR_SPECIFIC','냉각·기계설비 공간 면적',0),
 ('md_ups_battery','UPS_BATTERY_AREA','UPS·배터리실 면적','md_dc_family','AREA','DATA_CENTER','M2','ADDITIVE','SECTOR_SPECIFIC','UPS와 배터리 설비 공간 면적',0),
 ('md_dc_support','DATA_CENTER_SUPPORT_AREA','데이터센터 지원공간면적','md_dc_family','AREA','DATA_CENTER','M2','ADDITIVE','SECTOR_SPECIFIC','보안·물류·운영지원 등 비 IT 지원공간 면적',0),
 ('md_dc_office','DATA_CENTER_OFFICE_AREA','데이터센터 사무공간면적','md_dc_family','AREA','DATA_CENTER','M2','ADDITIVE','SECTOR_SPECIFIC','데이터센터 운영 사무공간 면적',0),

 ('md_retail_gla','RETAIL_GLA','리테일 총임대가능면적','md_retail_family','AREA','RETAIL','M2','SEMI_ADDITIVE','SECTOR_SPECIFIC','리테일 시설의 총임대가능면적',0),
 ('md_sales_floor','SALES_FLOOR_AREA','영업·매장면적','md_retail_family','AREA','RETAIL','M2','ADDITIVE','SECTOR_SPECIFIC','고객 대상 판매·영업 공간 면적',0),
 ('md_retail_boh','RETAIL_BACK_OF_HOUSE_AREA','리테일 후방면적','md_retail_family','AREA','RETAIL','M2','ADDITIVE','SECTOR_SPECIFIC','창고·준비·직원 등 후방 공간 면적',0),
 ('md_fnb_area','FNB_AREA','F&B 면적','md_retail_family','AREA','RETAIL','M2','ADDITIVE','SECTOR_SPECIFIC','식음 매장·조리·좌석 공간 면적',0),

 ('md_guestroom_area','GUESTROOM_AREA','객실면적','md_hosp_family','AREA','HOSPITALITY_LIVING','M2','ADDITIVE','SECTOR_SPECIFIC','호텔 객실 내부 면적',0),
 ('md_living_unit_area','LIVING_UNIT_AREA','주거 유닛면적','md_hosp_family','AREA','HOSPITALITY_LIVING','M2','ADDITIVE','SECTOR_SPECIFIC','임대주택·리빙 개별 유닛 면적',0),
 ('md_amenity_area','AMENITY_AREA','어메니티면적','md_hosp_family','AREA','HOSPITALITY_LIVING','M2','ADDITIVE','SECTOR_SPECIFIC','입주자·투숙객 편의시설 면적',0),
 ('md_public_area','PUBLIC_AREA','공공·공용부 면적','md_hosp_family','AREA','HOSPITALITY_LIVING','M2','SEMI_ADDITIVE','SECTOR_SPECIFIC','로비·복도 등 공용 고객 공간 면적',0),
 ('md_hotel_boh','HOTEL_BACK_OF_HOUSE_AREA','호텔 후방면적','md_hosp_family','AREA','HOSPITALITY_LIVING','M2','ADDITIVE','SECTOR_SPECIFIC','주방·린넨·직원·서비스 후방 공간 면적',0);

INSERT INTO measurement_definition_aliases(
 measurement_definition_id,alias_text,normalized_alias,asset_class_id,source_context,
 mapping_confidence,requires_review,example_text
) VALUES
 ('md_land_area','토지면적','토지면적',NULL,NULL,1.0,0,NULL),
 ('md_site_area','대지면적','대지면적',NULL,'건축·대장',1.0,0,NULL),
 ('md_project_site_area','부지면적','부지면적',NULL,'개발사업',0.90,1,'사업부지인지 개별 대지인지 문맥 확인'),
 ('md_project_site_area','사업면적','사업면적',NULL,'개발사업',0.80,1,NULL),
 ('md_footprint_area','건축면적','건축면적',NULL,NULL,1.0,0,NULL),
 ('md_gfa','연면적','연면적',NULL,NULL,1.0,0,NULL),
 ('md_gfa','GFA','gfa',NULL,NULL,0.95,0,NULL),
 ('md_far_gfa','용적률산정연면적','용적률산정연면적',NULL,NULL,1.0,0,NULL),
 ('md_floor_area','층별면적','층별면적',NULL,NULL,1.0,0,NULL),
 ('md_floor_plate','floor plate','floorplate',NULL,'오피스',0.90,0,NULL),
 ('md_typical_floor','기준층면적','기준층면적',NULL,NULL,1.0,0,NULL),
 ('md_typical_floor','typical floor plate','typicalfloorplate','ac_office',NULL,0.95,0,NULL),
 ('md_exclusive_area','전용면적','전용면적',NULL,NULL,1.0,0,NULL),
 ('md_common_area','공용면적','공용면적',NULL,NULL,1.0,0,NULL),
 ('md_gla','GLA','gla',NULL,NULL,0.85,1,'리테일 GLA와 공통 총임대가능면적 구분'),
 ('md_nla','NLA','nla',NULL,NULL,0.95,0,NULL),
 ('md_rentable_area','임대면적','임대면적',NULL,NULL,0.75,1,'임대가능·실제 임차·계약면적 구분'),
 ('md_leased_area','임차면적','임차면적',NULL,'임대차',0.90,1,NULL),
 ('md_warehouse_area','창고면적','창고면적','ac_logistics',NULL,1.0,0,NULL),
 ('md_storage_area','보관면적','보관면적','ac_logistics',NULL,0.90,1,'창고 전체와 실제 보관구역 구분'),
 ('md_effective_storage','적재면적','적재면적','ac_logistics',NULL,0.80,1,'유효 적재면적 여부 확인'),
 ('md_ambient_storage','상온면적','상온면적','ac_logistics',NULL,0.90,1,NULL),
 ('md_cold_storage','저온면적','저온면적','ac_logistics',NULL,0.90,1,NULL),
 ('md_frozen_storage','냉동면적','냉동면적','ac_logistics',NULL,0.95,0,NULL),
 ('md_loading_area','하역면적','하역면적','ac_logistics',NULL,1.0,0,NULL),
 ('md_dock_area','도크면적','도크면적','ac_logistics',NULL,1.0,0,NULL),
 ('md_ramp_area','램프면적','램프면적','ac_logistics',NULL,1.0,0,NULL),
 ('md_white_space','화이트스페이스','화이트스페이스','ac_dc',NULL,0.95,0,NULL),
 ('md_data_hall','데이터홀면적','데이터홀면적','ac_dc',NULL,1.0,0,NULL),
 ('md_data_hall','상면면적','상면면적','ac_dc','서버랙·데이터홀',0.75,1,'화이트스페이스·랙 설치구역 여부 확인'),
 ('md_sales_floor','상면면적','상면면적','ac_retail','매장·영업',0.70,1,'리테일 영업면적 의미인지 확인'),
 ('md_server_room','서버실면적','서버실면적','ac_dc',NULL,1.0,0,NULL),
 ('md_mmr_area','MMR면적','mmr면적','ac_dc',NULL,1.0,0,NULL),
 ('md_electrical_room','전기실면적','전기실면적','ac_dc',NULL,1.0,0,NULL),
 ('md_mechanical_room','기계실면적','기계실면적','ac_dc',NULL,1.0,0,NULL),
 ('md_retail_gla','GLA','gla','ac_retail','리테일',0.95,0,NULL),
 ('md_sales_floor','영업면적','영업면적','ac_retail',NULL,0.95,0,NULL),
 ('md_sales_floor','매장면적','매장면적','ac_retail',NULL,0.95,0,NULL),
 ('md_guestroom_area','객실면적','객실면적','ac_hotel',NULL,1.0,0,NULL),
 ('md_living_unit_area','세대전용면적','세대전용면적','ac_living',NULL,0.95,0,NULL);

INSERT INTO measurement_definition_relations(
 subject_definition_id,relation_code,object_definition_id,relation_note,confidence
) VALUES
 ('md_gfa_above','COMPONENT_OF','md_gfa','지상 연면적은 전체 연면적의 구성값',1.0),
 ('md_gfa_below','COMPONENT_OF','md_gfa','지하 연면적은 전체 연면적의 구성값',1.0),
 ('md_nla','CLOSE_TO','md_rentable_area','출처 기준에 따라 순임대가능면적과 임대면적이 유사 사용',0.7),
 ('md_retail_gla','CLOSE_TO','md_gla','리테일 문맥의 GLA',0.9),
 ('md_effective_storage','COMPONENT_OF','md_storage_area','실제 적재 가능 부분',0.9),
 ('md_ambient_storage','COMPONENT_OF','md_storage_area','온도대별 보관 구성값',1.0),
 ('md_cold_storage','COMPONENT_OF','md_storage_area','온도대별 보관 구성값',1.0),
 ('md_frozen_storage','COMPONENT_OF','md_cold_storage','냉동을 저온과 별도 관리',0.9),
 ('md_data_hall','CLOSE_TO','md_white_space','출처에 따라 동의 또는 포함 관계일 수 있음',0.7),
 ('md_server_room','CLOSE_TO','md_data_hall','소형 시설에서 혼용될 수 있으나 동일시하지 않음',0.6),
 ('md_mmr_area','COMPONENT_OF','md_dc_family','데이터센터 기능공간 구성값',1.0),
 ('md_electrical_room','COMPONENT_OF','md_dc_family','데이터센터 기능공간 구성값',1.0),
 ('md_mechanical_room','COMPONENT_OF','md_dc_family','데이터센터 기능공간 구성값',1.0),
 ('md_sales_floor','COMPONENT_OF','md_retail_gla','영업공간은 리테일 임대가능공간의 구성 또는 중첩값',0.7),
 ('md_retail_boh','EXCLUDES','md_sales_floor','후방공간과 고객 영업공간은 구분',1.0);

INSERT INTO measurement_applicability(measurement_definition_id,asset_class_id,applicability_code,note_text) VALUES
 ('md_site_area','ac_commercial','COMMON','대부분 자산군의 부지 기준'),
 ('md_gfa','ac_commercial','CORE','대부분 건축자산의 핵심 면적'),
 ('md_floor_area','ac_commercial','COMMON','동·층 상세가 있는 경우'),
 ('md_typical_floor','ac_office','CORE','오피스 임대·설계 핵심 지표'),
 ('md_nla','ac_office','CORE','오피스 순임대가능면적'),
 ('md_warehouse_area','ac_logistics','CORE',NULL),
 ('md_storage_area','ac_logistics','CORE',NULL),
 ('md_effective_storage','ac_logistics','COMMON',NULL),
 ('md_ambient_storage','ac_logistics','CORE',NULL),
 ('md_cold_storage','ac_logistics','CORE',NULL),
 ('md_frozen_storage','ac_logistics','OPTIONAL',NULL),
 ('md_loading_area','ac_logistics','COMMON',NULL),
 ('md_dock_area','ac_logistics','COMMON',NULL),
 ('md_ramp_area','ac_logistics','COMMON',NULL),
 ('md_white_space','ac_dc','CORE',NULL),
 ('md_data_hall','ac_dc','CORE',NULL),
 ('md_server_room','ac_dc','COMMON',NULL),
 ('md_mmr_area','ac_dc','COMMON',NULL),
 ('md_electrical_room','ac_dc','CORE',NULL),
 ('md_mechanical_room','ac_dc','CORE',NULL),
 ('md_ups_battery','ac_dc','COMMON',NULL),
 ('md_retail_gla','ac_retail','CORE',NULL),
 ('md_sales_floor','ac_retail','CORE',NULL),
 ('md_retail_boh','ac_retail','COMMON',NULL),
 ('md_guestroom_area','ac_hotel','CORE',NULL),
 ('md_amenity_area','ac_hotel','COMMON',NULL),
 ('md_living_unit_area','ac_living','CORE',NULL);

INSERT INTO spatial_unit_types(spatial_unit_type_id,code,name_ko,parent_type_id,is_physical,is_repeatable) VALUES
 ('sut_root','ROOT','공간 루트',NULL,0,0),
 ('sut_site','SITE','부지','sut_root',1,1),
 ('sut_parcel','PARCEL','필지','sut_site',1,1),
 ('sut_building','BUILDING','동·건물','sut_site',1,1),
 ('sut_wing','WING','윙·구획동','sut_building',1,1),
 ('sut_floor','FLOOR','층','sut_building',1,1),
 ('sut_unit','UNIT','호·유닛','sut_floor',1,1),
 ('sut_zone','ZONE','기능구역','sut_floor',1,1),
 ('sut_roof','ROOF','옥상','sut_building',1,0),
 ('sut_exterior','EXTERIOR','외부공간','sut_site',1,1),
 ('sut_warehouse','WAREHOUSE_ZONE','창고구역','sut_zone',1,1),
 ('sut_storage','STORAGE_ZONE','보관·적재구역','sut_warehouse',1,1),
 ('sut_loading','LOADING_ZONE','하역구역','sut_zone',1,1),
 ('sut_dock','DOCK','도크','sut_loading',1,1),
 ('sut_ramp','RAMP','램프','sut_zone',1,1),
 ('sut_cold','COLD_STORAGE_ZONE','저온·냉동구역','sut_storage',1,1),
 ('sut_data_hall','DATA_HALL','데이터홀','sut_zone',1,1),
 ('sut_server_room','SERVER_ROOM','서버실','sut_zone',1,1),
 ('sut_mmr','MEET_ME_ROOM','MMR','sut_zone',1,1),
 ('sut_electrical','ELECTRICAL_ROOM','전기실','sut_zone',1,1),
 ('sut_mechanical','MECHANICAL_ROOM','기계실','sut_zone',1,1),
 ('sut_support','SUPPORT_ZONE','지원구역','sut_zone',1,1),
 ('sut_sales_floor','SALES_FLOOR','영업·매장구역','sut_zone',1,1),
 ('sut_boh','BACK_OF_HOUSE','후방구역','sut_zone',1,1),
 ('sut_guestroom','GUESTROOM','객실','sut_unit',1,1),
 ('sut_amenity','AMENITY_ZONE','어메니티구역','sut_zone',1,1);

INSERT INTO measurement_dimension_definitions(
 measurement_dimension_id,code,name_ko,value_kind,dimension_group,description,is_multivalued
) VALUES
 ('dim_floor_label','FLOOR_LABEL','층 표기','TEXT','SPATIAL_SCOPE','원문 층 표기 또는 층 범위',0),
 ('dim_project_phase','PROJECT_PHASE','사업 단계·차수','TEXT','PROJECT_SCOPE','1단계·Phase 2 등 개발 단계',0),
 ('dim_standard','MEASUREMENT_STANDARD','측정 기준 문서','OPTION','BASIS','대장·허가·설계·준공·임대차·운영 등 기준',0),
 ('dim_temperature','TEMPERATURE_ZONE','온도대','OPTION','OPERATIONAL_SCOPE','상온·냉장·냉동 등 온도 조건',0),
 ('dim_tenancy','TENANCY_SCOPE','점유·임대 기준','OPTION','OCCUPANCY_SCOPE','총·순·전용·공용·임대·점유·공실 기준',0),
 ('dim_included','INCLUDED_COMPONENT','포함 항목','TEXT','COMPOSITION','측정값에 포함된 구성요소',1),
 ('dim_excluded','EXCLUDED_COMPONENT','제외 항목','TEXT','COMPOSITION','측정값에서 제외된 구성요소',1),
 ('dim_spatial_ref','RELATED_SPATIAL_UNIT','관련 공간단위','SPATIAL_UNIT','SPATIAL_SCOPE','본 측정의 보조 공간 범위',1),
 ('dim_source_revision','SOURCE_REVISION','출처 도면·문서 버전','TEXT','PROVENANCE','측정 근거 문서의 버전·개정번호',0),
 ('dim_is_representative','IS_REPRESENTATIVE','대표값 여부','BOOLEAN','STATISTICAL_SCOPE','기준층 등 대표값인지 여부',0);

INSERT INTO measurement_dimension_options(
 measurement_dimension_option_id,measurement_dimension_id,code,name_ko,sort_order
) VALUES
 ('mdo_std_register','dim_standard','BUILDING_REGISTER','건축물대장',10),
 ('mdo_std_permit','dim_standard','PERMIT_DRAWING','인허가 도면',20),
 ('mdo_std_design','dim_standard','DESIGN_DRAWING','설계도면',30),
 ('mdo_std_asbuilt','dim_standard','AS_BUILT_DRAWING','준공도면',40),
 ('mdo_std_lease','dim_standard','LEASE_ABSTRACT','임대차 문서',50),
 ('mdo_std_operation','dim_standard','OPERATION_REPORT','운영자료',60),
 ('mdo_std_appraisal','dim_standard','APPRAISAL','감정평가',70),
 ('mdo_temp_ambient','dim_temperature','AMBIENT','상온',10),
 ('mdo_temp_chilled','dim_temperature','CHILLED','냉장·저온',20),
 ('mdo_temp_frozen','dim_temperature','FROZEN','냉동',30),
 ('mdo_temp_multi','dim_temperature','MULTI_TEMPERATURE','복합온도대',40),
 ('mdo_tenancy_gross','dim_tenancy','GROSS','총면적 기준',10),
 ('mdo_tenancy_net','dim_tenancy','NET','순면적 기준',20),
 ('mdo_tenancy_exclusive','dim_tenancy','EXCLUSIVE','전용 기준',30),
 ('mdo_tenancy_common','dim_tenancy','COMMON','공용 기준',40),
 ('mdo_tenancy_rentable','dim_tenancy','RENTABLE','임대가능 기준',50),
 ('mdo_tenancy_occupied','dim_tenancy','OCCUPIED','점유 기준',60),
 ('mdo_tenancy_vacant','dim_tenancy','VACANT','공실 기준',70);

INSERT INTO event_categories(event_category_id, code, name_ko) VALUES
 ('cat_sale','SALE','매각'),
 ('cat_lease','LEASE','임대'),
 ('cat_supply','NEW_SUPPLY','신규공급'),
 ('cat_permit','PERMIT','인허가'),
 ('cat_pf','PF','PF'),
 ('cat_loan','LOAN','대출'),
 ('cat_invest','INVESTMENT','투자'),
 ('cat_corporate_relocation','CORPORATE_RELOCATION','기업 이전');

INSERT INTO event_stages(stage_code, event_category_id, name_ko, stage_rank, is_terminal) VALUES
 ('SALE_REVIEWED','cat_sale','매각 검토',10,0),
 ('ADVISOR_SELECTED','cat_sale','매각주관사 선정',20,0),
 ('MARKETING_STARTED','cat_sale','마케팅 개시',30,0),
 ('PRELIMINARY_BID','cat_sale','예비입찰',40,0),
 ('SHORTLISTED','cat_sale','숏리스트 확정',45,0),
 ('FINAL_BID','cat_sale','본입찰',50,0),
 ('PREFERRED_BIDDER_SELECTED','cat_sale','우선협상대상자 선정',60,0),
 ('MOU_SIGNED','cat_sale','양해각서 체결',63,0),
 ('DUE_DILIGENCE','cat_sale','실사·가격협상',66,0),
 ('CONTRACT_SIGNED','cat_sale','매매계약 체결',70,0),
 ('SPA_SIGNED','cat_sale','SPA 체결',72,0),
 ('CONDITIONS_PENDING','cat_sale','선행조건 충족 대기',75,0),
 ('CLOSED','cat_sale','거래 종결',80,1),
 ('SALE_WITHDRAWN','cat_sale','매각 철회',90,1),
 ('SALE_FAILED','cat_sale','거래 무산',95,1),
 ('REBID','cat_sale','재입찰',35,0),
 ('LEASE_MARKETING','cat_lease','임차인 모집',10,0),
 ('LEASE_NEGOTIATING','cat_lease','임대차 협상',20,0),
 ('LEASE_SIGNED','cat_lease','임대차 계약',30,0),
 ('TENANT_OCCUPIED','cat_lease','입주',40,1),
 ('PLANNED','cat_supply','공급 계획',10,0),
 ('UNDER_CONSTRUCTION','cat_supply','공사 중',20,0),
 ('COMPLETED','cat_supply','준공',30,0),
 ('USE_APPROVED','cat_supply','사용승인',40,0),
 ('OPENED','cat_supply','개장·운영 개시',50,1),
 ('PERMIT_FILED','cat_permit','인허가 접수',10,0),
 ('UNDER_REVIEW','cat_permit','심의 중',20,0),
 ('CONDITIONALLY_APPROVED','cat_permit','조건부 의결',30,0),
 ('PERMIT_APPROVED','cat_permit','인허가 승인',40,1),
 ('PERMIT_REJECTED','cat_permit','인허가 반려',50,1),
 ('BRIDGE_LOAN','cat_pf','브릿지론',10,0),
 ('MAIN_PF_ARRANGING','cat_pf','본PF 주선',20,0),
 ('MAIN_PF_COMMITTED','cat_pf','본PF 약정',30,0),
 ('PF_DRAWDOWN','cat_pf','PF 실행',40,0),
 ('PF_REFINANCED','cat_pf','PF 차환',50,0),
 ('PF_RESTRUCTURED','cat_pf','PF 재구조화',60,0),
 ('PF_REPAID','cat_pf','PF 상환',70,1),
 ('LOAN_MARKETING','cat_loan','대출 모집',10,0),
 ('LOAN_COMMITTED','cat_loan','대출 약정',20,0),
 ('LOAN_DRAWDOWN','cat_loan','대출 실행',30,0),
 ('LOAN_REFINANCED','cat_loan','대출 차환',40,0),
 ('LOAN_REPAID','cat_loan','대출 상환',50,1),
 ('INVESTMENT_REVIEWED','cat_invest','투자 검토',10,0),
 ('MANAGER_RFP_OPEN','cat_invest','위탁운용사 모집',12,0),
 ('MANAGER_SELECTED','cat_invest','위탁운용사 선정',15,0),
 ('INVESTMENT_COMMITTED','cat_invest','투자 약정',20,0),
 ('INVESTMENT_CLOSED','cat_invest','투자 집행',30,1),
 ('INVESTMENT_EXITED','cat_invest','투자 회수',40,1),
 ('RELOCATION_REPORTED','cat_corporate_relocation','이전 보도·검토',10,0),
 ('RELOCATION_ANNOUNCED','cat_corporate_relocation','이전 계획 발표',20,0),
 ('RELOCATION_SITE_SELECTED','cat_corporate_relocation','이전지 선정',30,0),
 ('RELOCATION_CONTRACTED','cat_corporate_relocation','이전 계약',40,0),
 ('RELOCATION_COMPLETED','cat_corporate_relocation','이전 완료',50,1),
 ('RELOCATION_CANCELLED','cat_corporate_relocation','이전 취소',60,1);

INSERT INTO mention_type_definitions(mention_type, name_ko, resolution_target, is_quantitative) VALUES
 ('ASSET','자산명','ASSET',0),
 ('PROJECT','사업·프로젝트명','PROJECT',0),
 ('ORGANIZATION','회사·기관·펀드명','ORGANIZATION',0),
 ('PERSON','인물명','ORGANIZATION',0),
 ('REGION','지역명','REGION',0),
 ('ADDRESS','주소','REGION',0),
 ('ASSET_CLASS','자산군','ASSET_CLASS',0),
 ('EVENT_STAGE','사건 단계','NONE',0),
 ('DATE','날짜','NONE',1),
 ('MONEY','금액','NONE',1),
 ('AREA','면적','NONE',1),
 ('PERCENT','비율','NONE',1),
 ('COUNT','수량','NONE',1),
 ('DURATION','기간','NONE',1),
 ('POWER','전력용량','NONE',1),
 ('OTHER_METRIC','기타 수치','NONE',1);

INSERT INTO predicate_definitions(predicate_code, name_ko, subject_scope, value_kind, default_unit_code, is_multivalued, description) VALUES
 ('ASSET_CLASS','자산군','ANY','ASSET_CLASS_REF',NULL,0,'표준 자산군 연결'),
 ('ROAD_ADDRESS','도로명주소','ASSET','TEXT',NULL,0,'원문 및 정규화 도로명주소'),
 ('SITE_AREA','대지면적','ANY','AREA','M2',0,'대지 또는 사업부지 면적'),
 ('GROSS_FLOOR_AREA','연면적','ANY','AREA','M2',0,'건물 또는 프로젝트 전체 연면적'),
 ('LEASABLE_AREA','임대가능면적','ASSET','AREA','M2',0,'임대 가능 면적'),
 ('LEASED_AREA','임차면적','EVENT','AREA','M2',1,'해당 임대차 사건의 계약 면적'),
 ('ROOM_COUNT','객실수','ASSET','COUNT','ROOM',0,'호텔·생활형 자산 객실수'),
 ('POWER_CAPACITY','전력용량','ANY','NUMBER','MW',1,'데이터센터 전력 또는 IT load'),
 ('ASKING_PRICE','희망가격','EVENT','MONEY','KRW',1,'매도자 또는 기사상 희망가'),
 ('APPRAISAL_VALUE','감정평가액','EVENT','MONEY','KRW',1,'감정평가 기준 가치'),
 ('BID_PRICE','입찰가격','EVENT','MONEY','KRW',1,'입찰 제출 금액'),
 ('BID_RANK','입찰순위','EVENT','NUMBER',NULL,1,'특정 입찰 라운드·평가시점의 보고 순위'),
 ('SALE_PROCESS_STATUS','매각절차 상태','EVENT','TEXT',NULL,1,'매각절차의 보고된 단계 또는 상태'),
 ('BID_CONDITIONS','입찰조건','EVENT','JSON',NULL,1,'가격 외 자금조달·실사·종결 조건'),
 ('FUNDING_STRUCTURE','인수자금 구조','EVENT','JSON',NULL,1,'펀드·SPC·LP·대주 등 입찰자금 구조'),
 ('DECISION_REASON','선정사유','EVENT','TEXT',NULL,1,'숏리스트·우협·차순위 선정의 가격·비가격 사유'),
 ('CONTRACT_PRICE','계약가격','EVENT','MONEY','KRW',1,'계약 체결 금액'),
 ('CLOSING_PRICE','종결가격','EVENT','MONEY','KRW',1,'잔금·소유권이전 기준 거래가'),
 ('PRICE_ESTIMATE','추정가격','EVENT','MONEY','KRW',1,'언론·시장 관계자 추정치'),
 ('RENT_AMOUNT','임대료','EVENT','MONEY','KRW',1,'임대료 금액'),
 ('DEPOSIT_AMOUNT','보증금','EVENT','MONEY','KRW',1,'임대차 보증금'),
 ('PF_COMMITMENT_AMOUNT','PF 약정액','EVENT','MONEY','KRW',1,'프로젝트금융 약정 총액'),
 ('PF_DRAWDOWN_AMOUNT','PF 실행액','EVENT','MONEY','KRW',1,'실제 인출·실행 금액'),
 ('LOAN_COMMITMENT_AMOUNT','대출 약정액','EVENT','MONEY','KRW',1,'일반 담보·인수금융 약정액'),
 ('LOAN_BALANCE','대출잔액','EVENT','MONEY','KRW',1,'기준일 현재 잔액'),
 ('INVESTMENT_COMMITMENT_AMOUNT','투자 약정액','EVENT','MONEY','KRW',1,'출자·투자 약정액'),
 ('INVESTMENT_EXECUTED_AMOUNT','투자 집행액','EVENT','MONEY','KRW',1,'실제 집행 금액'),
 ('LP_MANDATE_PROGRAM_AMOUNT','LP 위탁 프로그램 규모','EVENT','MONEY','KRW',1,'위탁운용 프로그램 전체 공고 규모'),
 ('LP_MANDATE_COMMITMENT_AMOUNT','LP 위탁 출자·배정액','EVENT','MONEY','KRW',1,'LP가 트랙·선정 운용사에 배정 또는 약정한 금액'),
 ('LP_MANDATE_TARGET_FUND_SIZE','위탁 펀드 목표규모','EVENT','MONEY','KRW',1,'LP 출자액과 구분되는 목표 펀드 결성 규모'),
 ('LP_MANDATE_TARGET_RETURN','위탁 투자 요구수익률','EVENT','PERCENT','PERCENT',1,'위탁운용 가이드라인의 목표·최소 수익률'),
 ('LP_MANDATE_GUIDELINE','위탁 투자 가이드라인','EVENT','TEXT',NULL,1,'전략·섹터·지역·기간·레버리지 등 투자지침'),
 ('LP_MANDATE_MANAGER_SELECTED','위탁운용사 선정','EVENT','ORGANIZATION_REF',NULL,1,'공개 절차에서 공식 확인된 운용사'),
 ('LP_MANDATE_REPORTED_SELECTED_MANAGER','보도된 유력 위탁운용사','EVENT','ORGANIZATION_REF',NULL,1,'공식 결과 미확인 상태에서 구체적 보도로 알려진 유력 운용사'),
 ('LP_MANDATE_REPORTED_MANAGER_ALLOCATION','보도된 선정사 배정금액','EVENT','MONEY','KRW',1,'공식 결과 미확인 상태에서 기사·리서치가 선정사별로 보도한 배정금액'),
 ('EVENT_DATE','사건 발생일','EVENT','DATE',NULL,0,'실제 사건 발생일'),
 ('EFFECTIVE_DATE','효력발생일','EVENT','DATE',NULL,0,'법적·계약상 효력일'),
 ('EXPECTED_COMPLETION_DATE','준공예정일','PROJECT','DATE',NULL,1,'예정 준공일'),
 ('COMPLETION_DATE','준공일','PROJECT','DATE',NULL,1,'실제 준공일'),
 ('USE_APPROVAL_DATE','사용승인일','ASSET','DATE',NULL,1,'사용승인 효력일'),
 ('VACANCY_RATE','공실률','ANY','PERCENT','PERCENT',1,'자산·권역 공실률'),
 ('CAP_RATE','Cap rate','EVENT','PERCENT','PERCENT',1,'거래 또는 시장 수익률'),
 ('INTEREST_RATE','금리','EVENT','PERCENT','PERCENT',1,'대출·PF 금리'),
 ('LTV','담보인정비율','EVENT','PERCENT','PERCENT',1,'LTV'),
 ('PARTICIPANT_ROLE','참여자 역할','EVENT','ORGANIZATION_REF',NULL,1,'매도자·매수자·대주 등 역할 연결'),
 ('BUSINESS_DOMAIN','사업영역','ORGANIZATION','TEXT',NULL,1,'시점별 주요 사업영역과 활동 설명'),
 ('INVESTMENT_PLAN_AMOUNT','투자계획 금액','EVENT','MONEY','KRW',1,'공식 또는 보도된 계획 단계 투자·CAPEX 금액'),
 ('INVESTMENT_PLAN_DESCRIPTION','투자계획 설명','EVENT','TEXT',NULL,1,'시설·인력·CAPEX 등 투자계획 원문'),
 ('HEADCOUNT_PLAN','인력 증감 계획','EVENT','COUNT','COUNT',1,'채용·감원·시설 인원 계획'),
 ('RELOCATION_ORIGIN','이전 출발지','EVENT','REGION_REF',NULL,1,'기업 이전 전 지역·자산'),
 ('RELOCATION_DESTINATION','이전 목적지','EVENT','REGION_REF',NULL,1,'기업 이전 후 지역·자산'),
 ('EXPECTED_MOVE_IN_DATE','입주 예정일','EVENT','DATE',NULL,1,'기사·공시·계약상 예상 입주시점');

INSERT INTO claim_role_definitions(role_code, name_ko, allowed_kind, description) VALUES
 ('ASSET','대상 자산','ANY','사건 또는 claim의 대상 물리 자산'),
 ('PROJECT','대상 프로젝트','ANY','개발·금융·투자 프로젝트'),
 ('BUYER','매수자','ANY','매입 주체'),
 ('SELLER','매도자','ANY','매각 주체'),
 ('OWNER','소유자','ANY','기준시점 소유 주체'),
 ('DEVELOPER','시행사','ANY','개발사업 시행 주체'),
 ('OPERATOR','운영사','ANY','자산 운영 주체'),
 ('TENANT','임차인','ANY','임차 주체'),
 ('LANDLORD','임대인','ANY','임대 주체'),
 ('LENDER','대주','ANY','대출·PF 제공 주체'),
 ('BORROWER','차주','ANY','대출·PF 조달 주체'),
 ('INVESTOR','투자자','ANY','투자 집행 주체'),
 ('ADVISOR','주관·자문사','ANY','매각·금융·법률 자문 주체'),
 ('SELL_SIDE_ADVISOR','매도측 자문사','ANY','매각주관·매도측 재무자문 주체'),
 ('BUY_SIDE_ADVISOR','매수측 자문사','ANY','입찰자 측 재무·투자 자문 주체'),
 ('LEGAL_ADVISOR','법률자문사','ANY','거래 법률자문 주체'),
 ('DEBT_ARRANGER','인수금융 주선사','ANY','인수금융 구조화·주선 주체'),
 ('BIDDER','입찰자','ANY','특정 라운드의 입찰 참여 주체'),
 ('CONSORTIUM_MEMBER','컨소시엄 구성원','ANY','공동 입찰 컨소시엄 참여자'),
 ('MANAGED_FUND','운용 펀드·리츠','ANY','운용사가 입찰에 사용하는 펀드·리츠'),
 ('ACQUISITION_VEHICLE','매수기구·SPC','ANY','인수 명의 및 자금 수취 기구'),
 ('EQUITY_PROVIDER','지분자금 제공자','ANY','LP·공동투자자 등 equity 제공 주체'),
 ('DEBT_PROVIDER','인수금융 제공자','ANY','담보·인수금융 대주 또는 대주단'),
 ('BID_ROUND','입찰 라운드','ANY','예비·본입찰·재입찰 등 평가 라운드'),
 ('BID_RANK','입찰 순위','ANY','해당 라운드·시점에 보도된 순위'),
 ('SHORTLISTED_PARTY','숏리스트 후보','ANY','적격인수후보 또는 숏리스트 포함 주체'),
 ('PREFERRED_BIDDER','우선협상대상자','ANY','현재 또는 과거 우선협상대상자'),
 ('RESERVE_BIDDER','차순위협상대상자','ANY','차순위 또는 예비 협상대상자'),
 ('FUNDING_SOURCE','자금조달 출처','ANY','입찰 또는 인수를 뒷받침하는 자금원'),
 ('LOCATION','지역·주소','ANY','사건·자산·프로젝트 위치'),
 ('PRICE','가격·금액','MENTION','거래가·호가·약정액 등 금액 표현'),
 ('AREA','면적','MENTION','대지·연면적·임대면적 등 면적 표현'),
 ('ANNOUNCEMENT_DATE','발표일','ANY','출처가 사건을 발표한 날짜'),
 ('EFFECTIVE_DATE','효력발생일','ANY','계약·승인 등의 실제 효력일'),
 ('EXPECTED_COMPLETION_DATE','준공예정일','ANY','계획 또는 예정 준공일'),
 ('SOURCE_STATE','이전 상태','ANY','상태전이 이전 단계'),
 ('TARGET_STATE','변경 상태','ANY','상태전이 이후 단계'),
 ('MANDATE_TRACK','위탁운용 트랙','TEXT','유력 선정사 claim이 속한 mandate track code'),
 ('RESOLUTION_STATUS','검증 판정상태','TEXT','LIKELY·HIGHLY_LIKELY·CONTRADICTED 등 검증대기 상태'),
 ('INDEPENDENT_FAMILY_COUNT','독립 출처계열 수','NUMBER','전재 중복 제거 후 독립 source family 수'),
 ('OCCURRENCE_COUNT','원문·전재 발견 수','NUMBER','동일 source family를 포함한 전체 발견 문서 수'),
 ('SUBJECT_ORGANIZATION','대상 조직','ENTITY','조직 단위 claim의 명시적 subject'),
 ('VERIFICATION_NEEDED','추가 검증 필요사항','TEXT','공식 결과·공시·당사자 확인 등 필요한 후속 근거');

INSERT INTO regions(region_id, region_type, canonical_name, parent_region_id, legal_dong_code, country_code) VALUES
 ('reg_kr','COUNTRY','대한민국',NULL,NULL,'KR'),
 ('reg_seoul','SIDO','서울특별시','reg_kr','11','KR'),
 ('reg_busan','SIDO','부산광역시','reg_kr','26','KR'),
 ('reg_daegu','SIDO','대구광역시','reg_kr','27','KR'),
 ('reg_incheon','SIDO','인천광역시','reg_kr','28','KR'),
 ('reg_gwangju','SIDO','광주광역시','reg_kr','29','KR'),
 ('reg_daejeon','SIDO','대전광역시','reg_kr','30','KR'),
 ('reg_ulsan','SIDO','울산광역시','reg_kr','31','KR'),
 ('reg_sejong','SIDO','세종특별자치시','reg_kr','36','KR'),
 ('reg_gyeonggi','SIDO','경기도','reg_kr','41','KR'),
 ('reg_chungbuk','SIDO','충청북도','reg_kr','43','KR'),
 ('reg_chungnam','SIDO','충청남도','reg_kr','44','KR'),
 ('reg_jeonnam','SIDO','전라남도','reg_kr','46','KR'),
 ('reg_gyeongbuk','SIDO','경상북도','reg_kr','47','KR'),
 ('reg_gyeongnam','SIDO','경상남도','reg_kr','48','KR'),
 ('reg_gangwon','SIDO','강원특별자치도','reg_kr','51','KR'),
 ('reg_jeonbuk','SIDO','전북특별자치도','reg_kr','52','KR'),
 ('reg_jeju','SIDO','제주특별자치도','reg_kr','50','KR');

INSERT INTO collection_sources(source_id, source_code, source_name, source_kind, base_url, authority_tier, collection_policy, policy_checked_at) VALUES
 ('src_google_news','GOOGLE_NEWS_RSS','Google News RSS','RSS','https://news.google.com/rss',4,'RSS_ONLY','2026-08-14'),
 ('src_naver_news','NAVER_NEWS_API','네이버 뉴스 검색 API','SEARCH_API','https://openapi.naver.com/v1/search/news.json',4,'API_ALLOWED','2026-08-14'),
 ('src_dart','OPENDART','OpenDART','OFFICIAL_API','https://opendart.fss.or.kr',1,'API_ALLOWED','2026-08-14'),
 ('src_vworld','VWORLD','VWorld','OFFICIAL_API','https://www.vworld.kr',1,'API_ALLOWED','2026-08-14'),
 ('src_buildinghub','BUILDING_HUB','건축HUB','OFFICIAL_API','https://www.data.go.kr',1,'API_ALLOWED','2026-08-14'),
 ('src_molit_rt','MOLIT_REAL_TRANSACTION','국토교통부 실거래 공개시스템','OFFICIAL_API','https://rt.molit.go.kr',1,'API_ALLOWED','2026-08-14'),
 ('src_bok','BOK_ECOS','한국은행 ECOS','STATISTICS','https://ecos.bok.or.kr',1,'API_ALLOWED','2026-08-14'),
 ('src_kosis','KOSIS','국가통계포털','STATISTICS','https://kosis.kr',1,'API_ALLOWED','2026-08-14');

INSERT INTO macro_series(macro_series_id, series_code, series_name_ko, metric_code, source_id, frequency_code, unit_code, region_id, adjustment_code, definition_text) VALUES
 ('ms_base_rate','BOK_BASE_RATE','한국은행 기준금리','INTEREST_RATE','src_bok','EVENT','PERCENT','reg_kr','NONE','한국은행 금융통화위원회가 결정한 기준금리'),
 ('ms_txn_count','CRE_TRANSACTION_COUNT_KR','상업용 부동산 거래건수','TRANSACTION_COUNT','src_molit_rt','MONTHLY','COUNT','reg_kr','NONE','국토교통부 공개자료에서 정의한 상업용 부동산 월간 거래건수'),
 ('ms_txn_amount','CRE_TRANSACTION_AMOUNT_KR','상업용 부동산 거래금액','TRANSACTION_AMOUNT','src_molit_rt','MONTHLY','KRW','reg_kr','NOMINAL','국토교통부 공개자료에서 정의한 상업용 부동산 월간 거래금액');

INSERT INTO predicate_relationship_rules(
    relationship_rule_id,predicate_code,claim_role_code,target_relation,
    participant_role_code,minimum_verification_status
) VALUES
    ('participant-role-tenant','PARTICIPANT_ROLE','TENANT','EVENT_PARTICIPANT','TENANT','VERIFIED'),
    ('participant-role-landlord','PARTICIPANT_ROLE','LANDLORD','EVENT_PARTICIPANT','LANDLORD','VERIFIED'),
    ('participant-role-owner','PARTICIPANT_ROLE','OWNER','EVENT_PARTICIPANT','OWNER','VERIFIED'),
    ('participant-role-operator','PARTICIPANT_ROLE','OPERATOR','EVENT_PARTICIPANT','OPERATOR','VERIFIED'),
    ('participant-role-investor','PARTICIPANT_ROLE','INVESTOR','EVENT_PARTICIPANT','INVESTOR','VERIFIED'),
    ('participant-role-buyer','PARTICIPANT_ROLE','BUYER','EVENT_PARTICIPANT','BUYER','VERIFIED'),
    ('participant-role-seller','PARTICIPANT_ROLE','SELLER','EVENT_PARTICIPANT','SELLER','VERIFIED'),
    ('business-domain-subject','BUSINESS_DOMAIN','SUBJECT_ORGANIZATION','BUSINESS_ACTIVITY',NULL,'VERIFIED');

INSERT INTO schema_meta(schema_key, schema_value) VALUES
 ('seed_version','2.7.0'),
 ('seeded_at','2026-08-14');

COMMIT;
