-- Development project 34-list snapshot for RA dashboard.
--
-- Purpose:
-- - Keep the 2026-06-30 development-project draft list in the same Supabase DB.
-- - Do not copy source project/fund/asset master rows.
-- - Store only a thin list plus links back to existing public.projects,
--   public.funds, and public.asset_master rows.
--
-- How to run:
-- - Paste this full file into Supabase SQL Editor and run once.
-- - The script is idempotent for the 2026-06-30 seed.

begin;

create table if not exists public.dev_project_extract_snapshots (
    snapshot_id text primary key,
    snapshot_date date not null,
    source_thread_id text,
    source_label text not null,
    source_asof_date date not null,
    list_count integer not null,
    extractor_version text not null default 'manual_sql_seed_v1',
    notes text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.dev_project_list (
    dev_project_id text primary key,
    list_no integer not null unique,
    source_category text not null check (source_category in ('PFV', 'Fund')),
    project_name text not null,
    vehicle_text text,
    inclusion_basis text not null,
    source_snapshot_id text not null references public.dev_project_extract_snapshots(snapshot_id) on delete restrict,
    source_thread_id text not null,
    source_asof_date date not null,
    match_status text not null default 'seeded',
    review_note text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.dev_project_project_links (
    dev_project_id text not null references public.dev_project_list(dev_project_id) on delete cascade,
    project_id text not null references public.projects(project_id) on delete restrict,
    project_name_snapshot text,
    relation_role text not null default 'primary_project',
    is_primary boolean not null default true,
    match_method text not null,
    match_confidence numeric(4, 2) not null check (match_confidence >= 0 and match_confidence <= 1),
    notes text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (dev_project_id, project_id)
);

create table if not exists public.dev_project_fund_links (
    dev_project_id text not null references public.dev_project_list(dev_project_id) on delete cascade,
    fund_id text not null references public.funds(fund_id) on delete restrict,
    short_name_snapshot text,
    fund_name_snapshot text,
    vehicle_role text not null default 'primary_vehicle',
    is_primary boolean not null default true,
    match_method text not null,
    match_confidence numeric(4, 2) not null check (match_confidence >= 0 and match_confidence <= 1),
    notes text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (dev_project_id, fund_id)
);

create table if not exists public.dev_project_asset_links (
    link_id bigint generated by default as identity primary key,
    dev_project_id text not null references public.dev_project_list(dev_project_id) on delete cascade,
    asset_id text not null references public.asset_master(asset_id) on delete restrict,
    canonical_name_snapshot text,
    asset_role text not null default 'related_asset',
    is_primary boolean not null default false,
    link_source text not null,
    link_source_id text not null,
    match_method text not null,
    match_confidence numeric(4, 2) not null check (match_confidence >= 0 and match_confidence <= 1),
    notes text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists dev_project_asset_links_unique_source
    on public.dev_project_asset_links(dev_project_id, asset_id, link_source, link_source_id);

create index if not exists dev_project_list_category_idx
    on public.dev_project_list(source_category, list_no);
create index if not exists dev_project_project_links_project_idx
    on public.dev_project_project_links(project_id);
create index if not exists dev_project_fund_links_fund_idx
    on public.dev_project_fund_links(fund_id);
create index if not exists dev_project_asset_links_asset_idx
    on public.dev_project_asset_links(asset_id);

comment on table public.dev_project_list is
    '2026-06-30 draft list of 34 development projects. One row is one list item, not one fund or asset.';
comment on table public.dev_project_project_links is
    'Thin links from dev_project_list rows to existing public.projects rows.';
comment on table public.dev_project_fund_links is
    'Thin links from dev_project_list rows to existing public.funds rows.';
comment on table public.dev_project_asset_links is
    'Derived or manually noted links from dev_project_list rows to existing public.asset_master rows.';

insert into public.dev_project_extract_snapshots (
    snapshot_id,
    snapshot_date,
    source_thread_id,
    source_label,
    source_asof_date,
    list_count,
    notes,
    metadata
) values (
    'dev_project_34_20260630',
    date '2026-06-30',
    '019f1258-6ba8-74b2-91d1-5b6f5c387529',
    'PFV/PFV-like plus development Fund draft list',
    date '2026-06-30',
    34,
    'Seeded from Codex thread conclusion: PFV/PFV-like 27 plus development Fund 7.',
    jsonb_build_object(
        'source_view', 'Project & Mission reporting view plus Excel cross-check',
        'list_basis', 'PFV/PFV-like 27 + development Fund 7',
        'caution', 'Numeric vehicle names must not be matched by substring only.'
    )
)
on conflict (snapshot_id) do update
set
    snapshot_date = excluded.snapshot_date,
    source_thread_id = excluded.source_thread_id,
    source_label = excluded.source_label,
    source_asof_date = excluded.source_asof_date,
    list_count = excluded.list_count,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

with seed_list (
    dev_project_id,
    list_no,
    source_category,
    project_name,
    vehicle_text,
    inclusion_basis,
    review_note
) as (
    values
    ('dp_001', 1, 'PFV', '울산역 KTX S3블럭 오피스텔 개발사업', 'P울산KTX', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_002', 2, 'PFV', '안녕인사동', 'P로터스, 120호, 121호', 'PFV/PFV-like project from Project & Mission list', 'Multiple vehicles are expected.'),
    ('dp_003', 3, 'PFV', '팩토리얼 성수', 'P성수PFV1', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_004', 4, 'PFV', '안성 성은 물류센터', 'P안성성은물류', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_005', 5, 'PFV', '제주 화북 프로젝트', 'P디에스', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_006', 6, 'PFV', '은평 시니어리빙 1호', 'P은평진관동', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_007', 7, 'PFV', '공주시 공동주택 개발사업', 'P트리니티공주', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_008', 8, 'PFV', '상봉동 청년주택', 'P상봉IRD', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_009', 9, 'PFV', '오산세교 주상복합 개발사업', 'P오산세교아트', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_010', 10, 'PFV', '수서역 환승센터 복합개발사업', 'P수서역환승센터', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_011', 11, 'PFV', '효제동 주거복합 개발사업', 'P효제아트', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_012', 12, 'PFV', '서리풀 개발사업', 'P에스비씨', 'PFV/PFV-like project from Project & Mission list', 'Do not match HSBC rows by SBC substring.'),
    ('dp_013', 13, 'PFV', '세운5구역 개발사업', 'P세운5구역, 454호, 462호', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_014', 14, 'PFV', '을지로3가 10지구', 'P을지로95', 'PFV/PFV-like project from Project & Mission list', 'Do not match unrelated 95호/295호/395호 funds.'),
    ('dp_015', 15, 'PFV', '판교 제2테크노밸리 C1, C2블록 아이스퀘어 개발사업', 'P아이스퀘어', 'PFV/PFV-like project from Project & Mission list', 'Related D/E block assets may appear separately.'),
    ('dp_016', 16, 'PFV', '효제동 주거용 오피스텔', 'P효제센트럴', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_017', 17, 'PFV', '부산 해운대구 중동 공동주택 개발', 'P해운대센트럴', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_018', 18, 'PFV', '부천 소사 공동주택 개발사업', 'P부천소사', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_019', 19, 'PFV', '부림빌딩', 'P이든센트럴', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_020', 20, 'PFV', '청라 오피스텔 개발사업', 'P청라아트', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_021', 21, 'PFV', '천안 성성7지구 공동주택 개발사업', 'P천안성성동', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_022', 22, 'PFV', '이오타서울 816', 'P와이디816', 'PFV/PFV-like project from Project & Mission list', 'Fund exists but asset relationship is sparse; manual asset candidates are seeded.'),
    ('dp_023', 23, 'PFV', '이오타서울 427', 'P와이디427', 'PFV/PFV-like project from Project & Mission list', 'Do not match unrelated 427호 fund by number alone.'),
    ('dp_024', 24, 'PFV', '동부산 테마파크 개발사업', 'P오시리아테마파크', 'PFV/PFV-like project from Project & Mission list', 'Ossiria tower residence is retained as related vehicle/project.'),
    ('dp_025', 25, 'PFV', '애월 복합관광단지 개발사업', '애월PFV', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_026', 26, 'PFV', '구리시 수택동 주거용 오피스텔 개발사업', 'P수택센트럴', 'PFV/PFV-like project from Project & Mission list', null),
    ('dp_027', 27, 'PFV', '팩토리얼 용산(용산 나진상가 재개발)', '567호 / 용산라이프시티PFV', 'Excel cross-check added PFV-like project already present in Notion', null),
    ('dp_028', 28, 'Fund', '서여의도 임대주택 개발사업', '395호', 'Development project held through Fund/REF vehicle', 'Excel name: 신동해빌딩 임대주택개발(NICE2).'),
    ('dp_029', 29, 'Fund', '가산동 임대형 기숙사 개발사업', '542호', 'Development project held through Fund/REF vehicle', null),
    ('dp_030', 30, 'Fund', '더케이호텔 재개발', '랜드마크부동산', 'Development project held through Fund/REF vehicle', 'Excel name: The K 호텔서울 재개발.'),
    ('dp_031', 31, 'Fund', '부산 송정 물류센터', '114호', 'Development project held through Fund/REF vehicle', null),
    ('dp_032', 32, 'Fund', '마곡 명소화 부지 개발사업', '420호', 'Development project held through Fund/REF vehicle', 'Business-stage management candidate.'),
    ('dp_033', 33, 'Fund', '포천 정교리 물류', '560호', 'Development project held through Fund/REF vehicle', 'Excel spelling may appear as 포천 청교리.'),
    ('dp_034', 34, 'Fund', '부산 육양국 DC', '572호', 'Development project held through Fund/REF vehicle', 'Notion project and 572호 fund exist; asset name is 명지녹산데이터센터개발사업.')
)
insert into public.dev_project_list (
    dev_project_id,
    list_no,
    source_category,
    project_name,
    vehicle_text,
    inclusion_basis,
    source_snapshot_id,
    source_thread_id,
    source_asof_date,
    match_status,
    review_note,
    metadata
)
select
    dev_project_id,
    list_no,
    source_category,
    project_name,
    vehicle_text,
    inclusion_basis,
    'dev_project_34_20260630',
    '019f1258-6ba8-74b2-91d1-5b6f5c387529',
    date '2026-06-30',
    'seeded',
    review_note,
    jsonb_build_object('seed_source', '2026-06-30 SQL Editor seed')
from seed_list
on conflict (dev_project_id) do update
set
    list_no = excluded.list_no,
    source_category = excluded.source_category,
    project_name = excluded.project_name,
    vehicle_text = excluded.vehicle_text,
    inclusion_basis = excluded.inclusion_basis,
    source_snapshot_id = excluded.source_snapshot_id,
    source_thread_id = excluded.source_thread_id,
    source_asof_date = excluded.source_asof_date,
    match_status = excluded.match_status,
    review_note = excluded.review_note,
    metadata = excluded.metadata,
    updated_at = now();

with seed_project_links (
    dev_project_id,
    project_id,
    relation_role,
    is_primary,
    match_method,
    match_confidence,
    notes
) as (
    values
    ('dp_001', 'project_notion_3258ced4-3c47-81a1-ae94-e9ff46be5503', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_002', 'project_notion_3258ced4-3c47-8154-b8d1-c4008b2d83ec', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_003', 'project_notion_3258ced4-3c47-814b-bf36-ec234ae43b2d', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_004', 'project_notion_3258ced4-3c47-8146-b3a1-e78b9a3806b0', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_005', 'project_notion_3258ced4-3c47-8119-9a2d-caecb456ac92', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_006', 'project_notion_3258ced4-3c47-817a-977f-f625bb42318f', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_007', 'project_notion_3258ced4-3c47-81f1-8acf-fa0dcf911205', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_008', 'project_notion_3258ced4-3c47-819d-90a9-ff29cc1de1d2', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_009', 'project_notion_3258ced4-3c47-81dc-9709-fa150a62a94b', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_010', 'project_notion_3258ced4-3c47-811e-8425-ec7178f406ba', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_011', 'project_notion_3258ced4-3c47-8144-a246-e143a4860886', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_012', 'project_notion_3258ced4-3c47-81aa-adde-cf3478b10198', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_013', 'project_notion_3258ced4-3c47-81fe-863b-d520374af4eb', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_014', 'project_notion_3258ced4-3c47-81f5-be7c-d44bb26eea52', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_015', 'project_notion_3258ced4-3c47-8157-b1ac-f58d211a8fef', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_015', 'project_notion_3258ced4-3c47-8190-9c2c-d9cdea369e36', 'related_project', false, 'verified_related_name_match', 0.90, '판교 아이스퀘어 D동 related row.'),
    ('dp_016', 'project_notion_3258ced4-3c47-817a-8987-ca5881e5effb', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_017', 'project_notion_3258ced4-3c47-81a2-8889-e0127ab86d9c', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_018', 'project_notion_3258ced4-3c47-814d-8058-c37ab0260495', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_019', 'project_notion_3258ced4-3c47-81af-974e-eb74e82227b7', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_020', 'project_notion_3258ced4-3c47-8174-9ccc-e400e5a2f47d', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_021', 'project_notion_3258ced4-3c47-8168-b61b-f37e347025ae', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_022', 'project_notion_3258ced4-3c47-81cb-a4ff-e9df05eb2777', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_022', 'iota-816', 'pilot_code', false, 'verified_pilot_code_match', 0.95, 'Pilot code row retained for IOTA Seoul.'),
    ('dp_023', 'project_notion_3258ced4-3c47-818d-9da5-c27149a74a92', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_023', 'iota-427', 'pilot_code', false, 'verified_pilot_code_match', 0.95, 'Pilot code row retained for IOTA Seoul.'),
    ('dp_024', 'project_notion_3258ced4-3c47-815c-b58b-f8dc2879e1ba', 'primary_project', true, 'verified_related_name_match', 0.93, 'DB project name is 오시리아 테마파크 2차 개발사업.'),
    ('dp_024', 'project_notion_3258ced4-3c47-8178-a538-d3245bf6d565', 'related_project', false, 'verified_related_name_match', 0.90, '오시리아타워레지던스 related row.'),
    ('dp_025', 'project_notion_3258ced4-3c47-81d0-aae6-fed0986cadd7', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_026', 'project_notion_3258ced4-3c47-81cd-b5e6-d5dbcfd4bc13', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_027', 'project_notion_3258ced4-3c47-8112-b036-c2173374bb23', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_028', 'project_notion_3258ced4-3c47-814e-8248-f4ca04db3fd1', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_029', 'project_notion_3258ced4-3c47-8136-96d3-f99474d7d46d', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_030', 'project_notion_3258ced4-3c47-81a5-a7f1-c3d4a6b8c43b', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_031', 'project_notion_3258ced4-3c47-8199-8f47-e575a5da4632', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_032', 'project_notion_3258ced4-3c47-81ed-a229-f6953c68328a', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_033', 'project_notion_3258ced4-3c47-8115-9bac-f9515d912ba0', 'primary_project', true, 'verified_name_match', 0.98, null),
    ('dp_034', 'project_notion_3258ced4-3c47-8146-a972-deb45e2e5bb9', 'primary_project', true, 'verified_name_match', 0.98, null)
)
insert into public.dev_project_project_links (
    dev_project_id,
    project_id,
    project_name_snapshot,
    relation_role,
    is_primary,
    match_method,
    match_confidence,
    notes,
    metadata
)
select
    s.dev_project_id,
    s.project_id,
    p.project_name,
    s.relation_role,
    s.is_primary,
    s.match_method,
    s.match_confidence,
    s.notes,
    jsonb_build_object('source', 'seed_project_links')
from seed_project_links s
join public.projects p
    on p.project_id = s.project_id
on conflict (dev_project_id, project_id) do update
set
    project_name_snapshot = excluded.project_name_snapshot,
    relation_role = excluded.relation_role,
    is_primary = excluded.is_primary,
    match_method = excluded.match_method,
    match_confidence = excluded.match_confidence,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

with seed_fund_links (
    dev_project_id,
    fund_id,
    vehicle_role,
    is_primary,
    match_method,
    match_confidence,
    notes
) as (
    values
    ('dp_001', 'P00034', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_002', 'P00007', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_002', '112114', 'supporting_fund_vehicle', false, 'verified_short_name_match', 0.98, '120호'),
    ('dp_002', '112115', 'supporting_fund_vehicle', false, 'verified_short_name_match', 0.98, '121호'),
    ('dp_003', 'P00010', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_004', 'P00014', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_005', 'P00028', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_006', 'P00033', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_007', 'P00025', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_008', 'P00019', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_009', 'P00012', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_010', 'P00027', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_011', 'P00009', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_012', 'P00005', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, 'Avoid HSBC false positives.'),
    ('dp_012', '112341', 'supporting_fund_vehicle', false, 'verified_project_mission_match', 0.92, '312호 linked to 에스비씨PFV.'),
    ('dp_012', '112532', 'supporting_fund_vehicle', false, 'verified_project_mission_match', 0.90, '409호 운용 linked to 이지스312호 수익증권.'),
    ('dp_013', 'P00006', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_013', '112641', 'supporting_fund_vehicle', false, 'verified_short_name_match', 0.98, '454호'),
    ('dp_013', '112661', 'supporting_fund_vehicle', false, 'verified_short_name_match', 0.98, '462호'),
    ('dp_014', 'P00029', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, 'Avoid unrelated 95호 fund.'),
    ('dp_015', 'P00001', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_015', '112535', 'supporting_fund_vehicle', false, 'verified_project_mission_match', 0.92, '407호'),
    ('dp_015', '112536', 'supporting_fund_vehicle', false, 'verified_project_mission_match', 0.92, '408호'),
    ('dp_016', 'P00022', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_017', 'P00035', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_018', 'P00008', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_019', 'P00032', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_020', 'P00015', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_021', 'P00017', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_022', 'P00037', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, 'Asset links are manual candidates because fund relationship is sparse.'),
    ('dp_023', 'P00030', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, 'Avoid unrelated 427호 fund.'),
    ('dp_023', '112614', 'supporting_fund_vehicle', false, 'verified_project_mission_match', 0.90, '421호 linked to 와이디427피에프브이.'),
    ('dp_024', 'P00002', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_024', 'P00003', 'related_pfv_vehicle', false, 'verified_related_short_name_match', 0.90, '오시리아타워레지던스 related PFV.'),
    ('dp_025', 'P00038', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_026', 'P00031', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, null),
    ('dp_027', 'P00039', 'primary_pfv_vehicle', true, 'verified_short_name_match', 0.99, '용산라이프시티PFV'),
    ('dp_027', '120074', 'supporting_fund_vehicle', false, 'verified_short_name_match', 0.98, '567호'),
    ('dp_027', '120099', 'supporting_fund_vehicle', false, 'verified_name_match', 0.92, '용산PF재구조화1호'),
    ('dp_028', '112514', 'primary_fund_vehicle', true, 'verified_short_name_match', 0.99, '395호 운용'),
    ('dp_028', '112515', 'share_class_vehicle', false, 'verified_short_name_match', 0.95, '395호(1종)'),
    ('dp_028', '112516', 'share_class_vehicle', false, 'verified_short_name_match', 0.95, '395호(2종)'),
    ('dp_029', '190005', 'primary_fund_vehicle', true, 'verified_short_name_match', 0.99, '542호'),
    ('dp_029', '190006', 'share_class_vehicle', false, 'verified_short_name_match', 0.95, '542호(1종)'),
    ('dp_029', '190007', 'share_class_vehicle', false, 'verified_short_name_match', 0.95, '542호(보통주식)'),
    ('dp_030', '190009', 'primary_fund_vehicle', true, 'verified_short_name_match', 0.99, '랜드마크부동산'),
    ('dp_030', '112143', 'related_fund_vehicle', false, 'verified_name_match', 0.85, '106호 재간접형 related row.'),
    ('dp_031', '112109', 'primary_fund_vehicle', true, 'verified_short_name_match', 0.99, '114호'),
    ('dp_032', '112579', 'primary_fund_vehicle', true, 'verified_short_name_match', 0.99, '420호 운용'),
    ('dp_032', '112580', 'share_class_vehicle', false, 'verified_short_name_match', 0.95, '420호(보통주)'),
    ('dp_032', '112581', 'share_class_vehicle', false, 'verified_short_name_match', 0.95, '420호(1종)'),
    ('dp_033', '190013', 'primary_fund_vehicle', true, 'verified_short_name_match', 0.99, '560호'),
    ('dp_034', '190014', 'primary_fund_vehicle', true, 'verified_short_name_match', 0.99, '572호 운용'),
    ('dp_034', '190015', 'share_class_vehicle', false, 'verified_short_name_match', 0.95, '572호(보통주)'),
    ('dp_034', '190016', 'share_class_vehicle', false, 'verified_short_name_match', 0.95, '572호(1종)')
)
insert into public.dev_project_fund_links (
    dev_project_id,
    fund_id,
    short_name_snapshot,
    fund_name_snapshot,
    vehicle_role,
    is_primary,
    match_method,
    match_confidence,
    notes,
    metadata
)
select
    s.dev_project_id,
    s.fund_id,
    f.short_name,
    f.fund_name,
    s.vehicle_role,
    s.is_primary,
    s.match_method,
    s.match_confidence,
    s.notes,
    jsonb_build_object(
        'source', 'seed_fund_links',
        'notion_vehicle_class', f.notion_vehicle_class,
        'notion_business_stage_class', f.notion_business_stage_class
    )
from seed_fund_links s
join public.funds f
    on f.fund_id = s.fund_id
on conflict (dev_project_id, fund_id) do update
set
    short_name_snapshot = excluded.short_name_snapshot,
    fund_name_snapshot = excluded.fund_name_snapshot,
    vehicle_role = excluded.vehicle_role,
    is_primary = excluded.is_primary,
    match_method = excluded.match_method,
    match_confidence = excluded.match_confidence,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

-- Rebuild generated asset links so the current source relationships are reflected.
delete from public.dev_project_asset_links
where link_source in (
    'projects.primary_asset_id',
    'projects.primary_asset_ids',
    'asset_project_links',
    'funds.primary_asset_id',
    'funds.primary_asset_ids',
    'asset_fund_links',
    'manual_burim_asset_candidate',
    'manual_iota816_asset_candidate'
);

insert into public.dev_project_asset_links (
    dev_project_id,
    asset_id,
    canonical_name_snapshot,
    asset_role,
    is_primary,
    link_source,
    link_source_id,
    match_method,
    match_confidence,
    notes,
    metadata
)
select distinct
    dpl.dev_project_id,
    p.primary_asset_id,
    am.canonical_name,
    case when dppl.is_primary then 'primary_project_asset' else 'related_project_asset' end,
    dppl.is_primary,
    'projects.primary_asset_id',
    p.project_id,
    'derived_from_project_primary_asset_id',
    0.95,
    null,
    jsonb_build_object('source_project_id', p.project_id)
from public.dev_project_project_links dppl
join public.dev_project_list dpl
    on dpl.dev_project_id = dppl.dev_project_id
join public.projects p
    on p.project_id = dppl.project_id
join public.asset_master am
    on am.asset_id = p.primary_asset_id
where p.primary_asset_id is not null
on conflict (dev_project_id, asset_id, link_source, link_source_id) do update
set
    canonical_name_snapshot = excluded.canonical_name_snapshot,
    asset_role = excluded.asset_role,
    is_primary = excluded.is_primary,
    match_method = excluded.match_method,
    match_confidence = excluded.match_confidence,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.dev_project_asset_links (
    dev_project_id,
    asset_id,
    canonical_name_snapshot,
    asset_role,
    is_primary,
    link_source,
    link_source_id,
    match_method,
    match_confidence,
    notes,
    metadata
)
select distinct
    dppl.dev_project_id,
    asset_id_item.asset_id,
    am.canonical_name,
    case when dppl.is_primary then 'primary_project_asset' else 'related_project_asset' end,
    dppl.is_primary,
    'projects.primary_asset_ids',
    p.project_id || ':' || asset_id_item.ordinality::text,
    'derived_from_project_primary_asset_ids',
    0.93,
    null,
    jsonb_build_object('source_project_id', p.project_id)
from public.dev_project_project_links dppl
join public.projects p
    on p.project_id = dppl.project_id
cross join lateral unnest(coalesce(p.primary_asset_ids, array[]::text[])) with ordinality as asset_id_item(asset_id, ordinality)
join public.asset_master am
    on am.asset_id = asset_id_item.asset_id
on conflict (dev_project_id, asset_id, link_source, link_source_id) do update
set
    canonical_name_snapshot = excluded.canonical_name_snapshot,
    asset_role = excluded.asset_role,
    is_primary = excluded.is_primary,
    match_method = excluded.match_method,
    match_confidence = excluded.match_confidence,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.dev_project_asset_links (
    dev_project_id,
    asset_id,
    canonical_name_snapshot,
    asset_role,
    is_primary,
    link_source,
    link_source_id,
    match_method,
    match_confidence,
    notes,
    metadata
)
select distinct
    dppl.dev_project_id,
    apl.asset_id,
    am.canonical_name,
    case when dppl.is_primary then 'project_linked_asset' else 'related_project_linked_asset' end,
    false,
    'asset_project_links',
    apl.project_id || ':' || apl.asset_id || ':' || coalesce(apl.relation_type, 'unknown'),
    'derived_from_asset_project_links',
    coalesce(apl.confidence, 0.90),
    null,
    jsonb_build_object(
        'source_project_id', apl.project_id,
        'relation_type', apl.relation_type,
        'resolution_status', apl.resolution_status
    )
from public.dev_project_project_links dppl
join public.asset_project_links apl
    on apl.project_id = dppl.project_id
join public.asset_master am
    on am.asset_id = apl.asset_id
on conflict (dev_project_id, asset_id, link_source, link_source_id) do update
set
    canonical_name_snapshot = excluded.canonical_name_snapshot,
    asset_role = excluded.asset_role,
    is_primary = excluded.is_primary,
    match_method = excluded.match_method,
    match_confidence = excluded.match_confidence,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.dev_project_asset_links (
    dev_project_id,
    asset_id,
    canonical_name_snapshot,
    asset_role,
    is_primary,
    link_source,
    link_source_id,
    match_method,
    match_confidence,
    notes,
    metadata
)
select distinct
    dpfl.dev_project_id,
    f.primary_asset_id,
    am.canonical_name,
    case when dpfl.is_primary then 'primary_vehicle_asset' else 'supporting_vehicle_asset' end,
    dpfl.is_primary,
    'funds.primary_asset_id',
    f.fund_id,
    'derived_from_fund_primary_asset_id',
    0.95,
    null,
    jsonb_build_object('source_fund_id', f.fund_id)
from public.dev_project_fund_links dpfl
join public.funds f
    on f.fund_id = dpfl.fund_id
join public.asset_master am
    on am.asset_id = f.primary_asset_id
where f.primary_asset_id is not null
on conflict (dev_project_id, asset_id, link_source, link_source_id) do update
set
    canonical_name_snapshot = excluded.canonical_name_snapshot,
    asset_role = excluded.asset_role,
    is_primary = excluded.is_primary,
    match_method = excluded.match_method,
    match_confidence = excluded.match_confidence,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.dev_project_asset_links (
    dev_project_id,
    asset_id,
    canonical_name_snapshot,
    asset_role,
    is_primary,
    link_source,
    link_source_id,
    match_method,
    match_confidence,
    notes,
    metadata
)
select distinct
    dpfl.dev_project_id,
    asset_id_item.asset_id,
    am.canonical_name,
    case when dpfl.is_primary then 'primary_vehicle_asset' else 'supporting_vehicle_asset' end,
    dpfl.is_primary,
    'funds.primary_asset_ids',
    f.fund_id || ':' || asset_id_item.ordinality::text,
    'derived_from_fund_primary_asset_ids',
    0.93,
    null,
    jsonb_build_object('source_fund_id', f.fund_id)
from public.dev_project_fund_links dpfl
join public.funds f
    on f.fund_id = dpfl.fund_id
cross join lateral unnest(coalesce(f.primary_asset_ids, array[]::text[])) with ordinality as asset_id_item(asset_id, ordinality)
join public.asset_master am
    on am.asset_id = asset_id_item.asset_id
on conflict (dev_project_id, asset_id, link_source, link_source_id) do update
set
    canonical_name_snapshot = excluded.canonical_name_snapshot,
    asset_role = excluded.asset_role,
    is_primary = excluded.is_primary,
    match_method = excluded.match_method,
    match_confidence = excluded.match_confidence,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.dev_project_asset_links (
    dev_project_id,
    asset_id,
    canonical_name_snapshot,
    asset_role,
    is_primary,
    link_source,
    link_source_id,
    match_method,
    match_confidence,
    notes,
    metadata
)
select distinct
    dpfl.dev_project_id,
    afl.asset_id,
    am.canonical_name,
    case when dpfl.is_primary then 'vehicle_linked_asset' else 'supporting_vehicle_linked_asset' end,
    false,
    'asset_fund_links',
    afl.fund_id || ':' || afl.asset_id || ':' || coalesce(afl.relation_type, 'unknown'),
    'derived_from_asset_fund_links',
    coalesce(afl.confidence, 0.90),
    null,
    jsonb_build_object(
        'source_fund_id', afl.fund_id,
        'relation_type', afl.relation_type,
        'exposure_role', afl.exposure_role,
        'allocation_status', afl.allocation_status
    )
from public.dev_project_fund_links dpfl
join public.asset_fund_links afl
    on afl.fund_id = dpfl.fund_id
join public.asset_master am
    on am.asset_id = afl.asset_id
on conflict (dev_project_id, asset_id, link_source, link_source_id) do update
set
    canonical_name_snapshot = excluded.canonical_name_snapshot,
    asset_role = excluded.asset_role,
    is_primary = excluded.is_primary,
    match_method = excluded.match_method,
    match_confidence = excluded.match_confidence,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

with manual_asset_links (
    dev_project_id,
    asset_id,
    canonical_name,
    link_source,
    source_fund_id,
    notes
) as (
    values
    ('dp_019', 'ast_f58dae267b1b', '을지로부림빌딩', 'manual_burim_asset_candidate', '112656', 'Manual candidate from 부림빌딩/을지로부림빌딩 asset and alias search.'),
    ('dp_022', 'ast_cd18ba041afc', '메트로타워', 'manual_iota816_asset_candidate', 'P00037', 'Manual candidate from P와이디816 asset_name text.'),
    ('dp_022', 'ast_47cfb7af7038', '서울로타워', 'manual_iota816_asset_candidate', 'P00037', 'Manual candidate from P와이디816 asset_name text.')
)
insert into public.dev_project_asset_links (
    dev_project_id,
    asset_id,
    canonical_name_snapshot,
    asset_role,
    is_primary,
    link_source,
    link_source_id,
    match_method,
    match_confidence,
    notes,
    metadata
)
select
    m.dev_project_id,
    m.asset_id,
    am.canonical_name,
    'manual_asset_candidate',
    false,
    m.link_source,
    m.asset_id,
    'manual_name_search',
    0.75,
    m.notes,
    jsonb_build_object('expected_name', m.canonical_name, 'source_fund_id', m.source_fund_id)
from manual_asset_links m
join public.asset_master am
    on am.asset_id = m.asset_id
on conflict (dev_project_id, asset_id, link_source, link_source_id) do update
set
    canonical_name_snapshot = excluded.canonical_name_snapshot,
    asset_role = excluded.asset_role,
    is_primary = excluded.is_primary,
    match_method = excluded.match_method,
    match_confidence = excluded.match_confidence,
    notes = excluded.notes,
    metadata = excluded.metadata,
    updated_at = now();

create or replace view public.dev_project_34_summary as
select
    dpl.list_no,
    dpl.dev_project_id,
    dpl.source_category,
    dpl.project_name,
    dpl.vehicle_text,
    dpl.inclusion_basis,
    dpl.review_note,
    coalesce(projects.project_count, 0) as linked_project_count,
    coalesce(funds.fund_count, 0) as linked_fund_count,
    coalesce(assets.asset_count, 0) as linked_asset_count,
    projects.project_ids,
    projects.project_names,
    funds.fund_ids,
    funds.short_names,
    funds.fund_names,
    assets.asset_ids,
    assets.asset_names
from public.dev_project_list dpl
left join lateral (
    select
        count(*) as project_count,
        array_agg(dppl.project_id order by dppl.is_primary desc, dppl.project_id) as project_ids,
        array_agg(dppl.project_name_snapshot order by dppl.is_primary desc, dppl.project_id) as project_names
    from public.dev_project_project_links dppl
    where dppl.dev_project_id = dpl.dev_project_id
) projects on true
left join lateral (
    select
        count(*) as fund_count,
        array_agg(dpfl.fund_id order by dpfl.is_primary desc, dpfl.fund_id) as fund_ids,
        array_agg(dpfl.short_name_snapshot order by dpfl.is_primary desc, dpfl.fund_id) as short_names,
        array_agg(dpfl.fund_name_snapshot order by dpfl.is_primary desc, dpfl.fund_id) as fund_names
    from public.dev_project_fund_links dpfl
    where dpfl.dev_project_id = dpl.dev_project_id
) funds on true
left join lateral (
    select
        count(distinct dpal.asset_id) as asset_count,
        array_agg(distinct dpal.asset_id) as asset_ids,
        array_agg(distinct dpal.canonical_name_snapshot) as asset_names
    from public.dev_project_asset_links dpal
    where dpal.dev_project_id = dpl.dev_project_id
) assets on true;

create or replace view public.dev_project_34_review_flags as
select
    s.list_no,
    s.dev_project_id,
    s.project_name,
    s.source_category,
    s.linked_project_count,
    s.linked_fund_count,
    s.linked_asset_count,
    array_remove(array[
        case when s.linked_project_count = 0 then 'missing_project_link' end,
        case when s.linked_fund_count = 0 then 'missing_fund_link' end,
        case when s.linked_asset_count = 0 then 'missing_asset_link' end,
        case when s.dev_project_id = 'dp_019' then 'manual_asset_candidate_needs_review' end,
        case when s.dev_project_id = 'dp_022' then 'manual_asset_candidates_need_review' end,
        case when s.project_name ilike '%서리풀%' then 'avoid_hsbc_false_positive' end,
        case when s.project_name ilike '%을지로3가%' then 'avoid_numeric_vehicle_false_positive' end,
        case when s.project_name ilike '%이오타서울 427%' then 'avoid_427ho_false_positive' end
    ], null) as review_flags
from public.dev_project_34_summary s
where s.linked_project_count = 0
   or s.linked_fund_count = 0
   or s.linked_asset_count = 0
   or s.dev_project_id in ('dp_012', 'dp_014', 'dp_019', 'dp_022', 'dp_023');

-- Keep these tables private by default. Service-role/API maintenance can still use them.
alter table public.dev_project_extract_snapshots enable row level security;
alter table public.dev_project_list enable row level security;
alter table public.dev_project_project_links enable row level security;
alter table public.dev_project_fund_links enable row level security;
alter table public.dev_project_asset_links enable row level security;

drop policy if exists dev_project_extract_snapshots_service_role_all on public.dev_project_extract_snapshots;
drop policy if exists dev_project_list_service_role_all on public.dev_project_list;
drop policy if exists dev_project_project_links_service_role_all on public.dev_project_project_links;
drop policy if exists dev_project_fund_links_service_role_all on public.dev_project_fund_links;
drop policy if exists dev_project_asset_links_service_role_all on public.dev_project_asset_links;

create policy dev_project_extract_snapshots_service_role_all
    on public.dev_project_extract_snapshots
    for all
    to service_role
    using (true)
    with check (true);

create policy dev_project_list_service_role_all
    on public.dev_project_list
    for all
    to service_role
    using (true)
    with check (true);

create policy dev_project_project_links_service_role_all
    on public.dev_project_project_links
    for all
    to service_role
    using (true)
    with check (true);

create policy dev_project_fund_links_service_role_all
    on public.dev_project_fund_links
    for all
    to service_role
    using (true)
    with check (true);

create policy dev_project_asset_links_service_role_all
    on public.dev_project_asset_links
    for all
    to service_role
    using (true)
    with check (true);

commit;

-- Verification queries. Run after the transaction succeeds.
select 'dev_project_list' as table_name, count(*) as row_count
from public.dev_project_list
where source_snapshot_id = 'dev_project_34_20260630'
union all
select 'dev_project_project_links', count(*) from public.dev_project_project_links
union all
select 'dev_project_fund_links', count(*) from public.dev_project_fund_links
union all
select 'dev_project_asset_links', count(*) from public.dev_project_asset_links;

select *
from public.dev_project_34_review_flags
order by list_no;
