from __future__ import annotations

import argparse
import json
import os
import sqlite3
import stat
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator, Sequence

from libsql_client import create_client_sync


def quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def load_dotenv(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
            value = value[1:-1]
        values[key] = value
    return values


def chunks(cursor: sqlite3.Cursor, size: int) -> Iterator[list[tuple[Any, ...]]]:
    while True:
        rows = cursor.fetchmany(size)
        if not rows:
            return
        yield rows


def source_table_types(conn: sqlite3.Connection) -> dict[str, str]:
    return {
        str(name): str(kind)
        for name, kind in conn.execute(
            "SELECT name, type FROM pragma_table_list "
            "WHERE schema='main' AND name NOT LIKE 'sqlite_%'"
        )
    }


def copy_database(source: sqlite3.Connection, target: Any, *, batch_rows: int) -> dict[str, int]:
    table_types = source_table_types(source)
    target_types = {
        str(name): str(kind)
        for name, kind in target.execute(
            "SELECT name, type FROM pragma_table_list "
            "WHERE schema='main' AND name NOT LIKE 'sqlite_%'"
        ).fetchall()
    }
    schema_rows = source.execute(
        "SELECT type, name, sql FROM sqlite_master "
        "WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL "
        "ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 "
        "WHEN 'trigger' THEN 2 WHEN 'view' THEN 3 ELSE 4 END, name"
    ).fetchall()

    # FTS shadow tables are generated by CREATE VIRTUAL TABLE; never replay them.
    for object_type, name, sql in schema_rows:
        if object_type != "table" or table_types.get(name) == "shadow":
            continue
        if name not in target_types:
            target.execute(sql)
    target.commit()

    copied: dict[str, int] = {}
    data_tables = sorted(name for name, kind in table_types.items() if kind in {"table", "virtual"})
    for name in data_tables:
        source_count = int(source.execute(f"SELECT count(*) FROM {quote_identifier(name)}").fetchone()[0])
        target_count = int(target.execute(f"SELECT count(*) FROM {quote_identifier(name)}").fetchone()[0])
        if target_count == source_count:
            copied[name] = source_count
            print(json.dumps({"table": name, "rows": source_count, "action": "verified_existing"}, ensure_ascii=False), flush=True)
            continue
        if target_count:
            raise RuntimeError(
                f"partial remote table requires reconciliation: {name} "
                f"source={source_count} remote={target_count}"
            )
        columns = [str(row[1]) for row in source.execute(f"PRAGMA table_info({quote_identifier(name)})")]
        if not columns:
            copied[name] = 0
            continue
        column_sql = ",".join(quote_identifier(col) for col in columns)
        placeholders = ",".join("?" for _ in columns)
        insert_sql = f"INSERT INTO {quote_identifier(name)} ({column_sql}) VALUES ({placeholders})"
        read_cursor = source.execute(f"SELECT {column_sql} FROM {quote_identifier(name)}")
        count = 0
        for batch in chunks(read_cursor, batch_rows):
            target.executemany(insert_sql, batch)
            target.commit()
            count += len(batch)
        copied[name] = count
        print(json.dumps({"table": name, "rows": count, "action": "inserted"}, ensure_ascii=False), flush=True)

    existing_objects = {
        (str(object_type), str(name))
        for object_type, name in target.execute(
            "SELECT type, name FROM sqlite_master WHERE name NOT LIKE 'sqlite_%'"
        ).fetchall()
    }
    for object_type, name, sql in schema_rows:
        if object_type in {"index", "trigger", "view"} and (object_type, name) not in existing_objects:
            target.execute(sql)
    target.commit()
    return copied


def remote_counts(client: Any, tables: list[str], *, chunk_size: int = 25) -> dict[str, int]:
    if not tables:
        return {}
    counts: dict[str, int] = {}
    for offset in range(0, len(tables), chunk_size):
        chunk = tables[offset : offset + chunk_size]
        statements = [
            f"SELECT '{table.replace(chr(39), chr(39) * 2)}' AS table_name, count(*) AS row_count "
            f"FROM {quote_identifier(table)}"
            for table in chunk
        ]
        result = client.execute(" UNION ALL ".join(statements))
        counts.update({str(row[0]): int(row[1]) for row in result.rows})
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(description="Publish a verified SQLite serving DB to an empty Turso DB")
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--replica", type=Path, required=True)
    parser.add_argument("--env-file", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--batch-rows", type=int, default=500)
    args = parser.parse_args()

    if args.batch_rows < 1:
        raise SystemExit("--batch-rows must be positive")
    env = load_dotenv(args.env_file)
    sync_url = env.get("TURSO_DATABASE_URL", "")
    auth_token = env.get("TURSO_AUTH_TOKEN", "")
    if not sync_url or not auth_token:
        raise SystemExit("TURSO_DATABASE_URL and TURSO_AUTH_TOKEN are required")
    http_url = sync_url.replace("libsql://", "https://", 1)

    source_uri = f"file:{args.source.resolve().as_posix()}?mode=ro"
    source = sqlite3.connect(source_uri, uri=True)
    try:
        integrity = str(source.execute("PRAGMA integrity_check").fetchone()[0])
        fk_violations = len(source.execute("PRAGMA foreign_key_check").fetchall())
        if integrity != "ok" or fk_violations:
            raise RuntimeError(f"source validation failed: integrity={integrity}, fk={fk_violations}")

        client = create_client_sync(http_url, auth_token=auth_token)
        try:
            existing = client.execute(
                "SELECT count(*) FROM sqlite_master WHERE name NOT LIKE 'sqlite_%'"
            ).rows[0][0]
            print(json.dumps({"remoteExistingObjects": int(existing)}, ensure_ascii=False), flush=True)
        finally:
            client.close()

        args.replica.parent.mkdir(parents=True, exist_ok=True)
        if args.replica.exists():
            os.chmod(args.replica, stat.S_IWRITE | stat.S_IREAD)

        import libsql

        target = libsql.connect(str(args.replica), sync_url=sync_url, auth_token=auth_token)
        try:
            target.sync()
            target.execute("PRAGMA foreign_keys=OFF")
            copied = copy_database(source, target, batch_rows=args.batch_rows)
            local_integrity = str(target.execute("PRAGMA integrity_check").fetchone()[0])
            local_fk = list(target.execute("PRAGMA foreign_key_check").fetchall())
            if local_integrity != "ok" or local_fk:
                raise RuntimeError(
                    f"replica validation failed: integrity={local_integrity}, fk={len(local_fk)}"
                )
            target.sync()
        finally:
            target.close()

        client = create_client_sync(http_url, auth_token=auth_token)
        try:
            remote = remote_counts(client, sorted(copied))
            mismatches = {
                name: {"source": copied[name], "remote": remote.get(name)}
                for name in copied
                if remote.get(name) != copied[name]
            }
            remote_fk = list(client.execute("PRAGMA foreign_key_check").rows)
            remote_integrity = str(client.execute("PRAGMA integrity_check").rows[0][0])
            object_rows = client.execute(
                "SELECT type, count(*) FROM sqlite_master "
                "WHERE name NOT LIKE 'sqlite_%' GROUP BY type ORDER BY type"
            ).rows
            if mismatches or remote_fk or remote_integrity != "ok":
                raise RuntimeError(
                    f"remote validation failed: mismatches={len(mismatches)}, "
                    f"fk={len(remote_fk)}, integrity={remote_integrity}"
                )
        finally:
            client.close()

        report = {
            "status": "COMPLETED",
            "completedAt": datetime.now(timezone.utc).isoformat(),
            "source": str(args.source.resolve()),
            "sourceBytes": args.source.stat().st_size,
            "sourceIntegrity": integrity,
            "sourceForeignKeyViolations": fk_violations,
            "tableCount": len(copied),
            "rowCount": sum(copied.values()),
            "tableRows": copied,
            "remoteObjectCounts": {str(row[0]): int(row[1]) for row in object_rows},
            "remoteIntegrity": remote_integrity,
            "remoteForeignKeyViolations": len(remote_fk),
            "rowCountMismatches": mismatches,
        }
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        os.chmod(args.replica, stat.S_IREAD)
        print(json.dumps({
            key: report[key]
            for key in (
                "status", "sourceBytes", "tableCount", "rowCount",
                "remoteIntegrity", "remoteForeignKeyViolations"
            )
        }, ensure_ascii=False))
    finally:
        source.close()


if __name__ == "__main__":
    main()